export const attitudeQuestions = [
  // ── Integrity ─────────────────────────────────────────────────────────────
  { subTopic: 'Integrity', text: 'You notice a colleague consistently taking credit for your work in meetings. What do you do first?', options: [{index:0,text:'Ignore it and hope it stops'},{index:1,text:'Confront them aggressively in the next meeting'},{index:2,text:'Privately address the issue with them directly'},{index:3,text:'Immediately escalate to HR'}], correctIndex: 2, difficulty: 0.2, discrimination: 1.3, guessing: 0.25, tags: ['integrity','conflict'] },
  { subTopic: 'Integrity', text: 'You made a mistake that caused a project delay. What is the best response?', options: [{index:0,text:'Say nothing and hope no one notices'},{index:1,text:'Blame the tools or process'},{index:2,text:'Acknowledge the mistake, explain what happened, and propose a fix'},{index:3,text:'Immediately resign'}], correctIndex: 2, difficulty: -0.5, discrimination: 1.4, guessing: 0.25, tags: ['integrity','accountability'] },
  { subTopic: 'Integrity', text: 'A manager asks you to falsify data in a report. You should:', options: [{index:0,text:'Do it since they are your manager'},{index:1,text:'Refuse and document your refusal'},{index:2,text:'Quietly tell a colleague'},{index:3,text:'Submit the report with the false data but add a disclaimer'}], correctIndex: 1, difficulty: -0.8, discrimination: 1.5, guessing: 0.25, tags: ['integrity','ethics'] },
  { subTopic: 'Integrity', text: 'You discover a billing error that benefits your company at a client\'s expense. What do you do?', options: [{index:0,text:'Say nothing — it benefits the company'},{index:1,text:'Report it to your manager to correct it'},{index:2,text:'Tell only your direct colleague'},{index:3,text:'Wait to see if the client notices'}], correctIndex: 1, difficulty: -0.3, discrimination: 1.4, guessing: 0.25, tags: ['integrity','ethics'] },
  { subTopic: 'Integrity', text: 'You are offered a gift by a vendor you oversee. The best action is:', options: [{index:0,text:'Accept it — it is just a gift'},{index:1,text:'Accept it but don\'t tell anyone'},{index:2,text:'Check company policy and decline or disclose it per policy'},{index:3,text:'Ask a colleague to accept it on your behalf'}], correctIndex: 2, difficulty: 0.4, discrimination: 1.3, guessing: 0.25, tags: ['integrity','compliance'] },

  // ── Work Ethic ───────────────────────────────────────────────────────────
  { subTopic: 'Work Ethic', text: 'You are given a deadline that seems unrealistic. What do you do?', options: [{index:0,text:'Agree and then miss the deadline'},{index:1,text:'Refuse the task'},{index:2,text:'Negotiate the deadline with data on scope, then commit to a realistic date'},{index:3,text:'Work 24 hours straight without telling anyone about the risk'}], correctIndex: 2, difficulty: 0.1, discrimination: 1.4, guessing: 0.25, tags: ['work-ethic','communication'] },
  { subTopic: 'Work Ethic', text: 'Your team finishes tasks early. What is the ideal response?', options: [{index:0,text:'Leave early since the work is done'},{index:1,text:'Look for ways to improve quality or help other team members'},{index:2,text:'Start working on tasks outside your role without telling anyone'},{index:3,text:'Wait for new assignments passively'}], correctIndex: 1, difficulty: 0.2, discrimination: 1.3, guessing: 0.25, tags: ['work-ethic','initiative'] },
  { subTopic: 'Work Ethic', text: 'You disagree with a decision made by leadership. What is the best approach?', options: [{index:0,text:'Publicly criticize the decision in meetings'},{index:1,text:'Ignore it and do things your own way'},{index:2,text:'Raise your concerns through appropriate channels, then commit to the decision'},{index:3,text:'Refuse to implement the decision'}], correctIndex: 2, difficulty: 0.3, discrimination: 1.4, guessing: 0.25, tags: ['work-ethic','professionalism'] },
  { subTopic: 'Work Ethic', text: 'A high-priority task conflicts with your planned vacation. How do you handle it?', options: [{index:0,text:'Cancel your vacation without informing anyone'},{index:1,text:'Discuss the conflict with your manager and explore options'},{index:2,text:'Ignore the task since you planned the vacation first'},{index:3,text:'Delegate everything without briefing the person'}], correctIndex: 1, difficulty: 0.0, discrimination: 1.3, guessing: 0.25, tags: ['work-ethic','prioritization'] },
  { subTopic: 'Work Ethic', text: 'You notice a process inefficiency that slows your team down. You should:', options: [{index:0,text:'Complain to colleagues but take no action'},{index:1,text:'Document the issue and propose a solution to your manager'},{index:2,text:'Change the process unilaterally'},{index:3,text:'Ignore it since it is not your problem'}], correctIndex: 1, difficulty: -0.1, discrimination: 1.4, guessing: 0.25, tags: ['work-ethic','initiative'] },

  // ── Adaptability ─────────────────────────────────────────────────────────
  { subTopic: 'Adaptability', text: 'Your company announces a major strategic pivot. Your first reaction should be:', options: [{index:0,text:'Start looking for a new job immediately'},{index:1,text:'Seek to understand the rationale, ask questions, and adapt your work accordingly'},{index:2,text:'Resist the change and continue with the old strategy'},{index:3,text:'Wait for others to react first'}], correctIndex: 1, difficulty: 0.1, discrimination: 1.4, guessing: 0.25, tags: ['adaptability','change'] },
  { subTopic: 'Adaptability', text: 'You are assigned to a project that requires skills you haven\'t fully developed yet. You:', options: [{index:0,text:'Decline the project'},{index:1,text:'Accept it and ask for training resources or mentorship'},{index:2,text:'Accept it and pretend you have all the skills'},{index:3,text:'Ask for an easier assignment'}], correctIndex: 1, difficulty: -0.2, discrimination: 1.4, guessing: 0.25, tags: ['adaptability','growth'] },
  { subTopic: 'Adaptability', text: 'Your team switches to a new software tool mid-project. You:', options: [{index:0,text:'Refuse to use the new tool'},{index:1,text:'Use only the old tool and reconcile manually'},{index:2,text:'Learn the new tool quickly and share tips with the team'},{index:3,text:'Ask to be moved to a different project'}], correctIndex: 2, difficulty: -0.3, discrimination: 1.3, guessing: 0.25, tags: ['adaptability','technology'] },
  { subTopic: 'Adaptability', text: 'You receive critical feedback on work you are proud of. You:', options: [{index:0,text:'Dismiss the feedback as wrong'},{index:1,text:'Get defensive and explain why you did it that way'},{index:2,text:'Listen actively, ask clarifying questions, and incorporate valid points'},{index:3,text:'Apologize excessively and redo everything from scratch'}], correctIndex: 2, difficulty: 0.2, discrimination: 1.4, guessing: 0.25, tags: ['adaptability','feedback'] },
  { subTopic: 'Adaptability', text: 'Priorities shift suddenly and your work becomes obsolete. You:', options: [{index:0,text:'Continue the original task anyway'},{index:1,text:'Express frustration loudly to the team'},{index:2,text:'Quickly assess impact, document what was done, and pivot to the new priority'},{index:3,text:'Wait to be reassigned without doing anything'}], correctIndex: 2, difficulty: 0.3, discrimination: 1.4, guessing: 0.25, tags: ['adaptability','agility'] },

  // ── Collaboration ─────────────────────────────────────────────────────────
  { subTopic: 'Collaboration', text: 'A team member is struggling with their tasks. You:', options: [{index:0,text:'Report it to the manager'},{index:1,text:'Ignore it — it is their problem'},{index:2,text:'Offer to help and share relevant knowledge'},{index:3,text:'Take over all their tasks without asking'}], correctIndex: 2, difficulty: -0.4, discrimination: 1.3, guessing: 0.25, tags: ['collaboration','teamwork'] },
  { subTopic: 'Collaboration', text: 'You strongly disagree with a team decision made by consensus. You:', options: [{index:0,text:'Do it your own way and explain later'},{index:1,text:'Openly record your objection, then commit to the team decision'},{index:2,text:'Sabotage the decision to prove it wrong'},{index:3,text:'Leave the team'}], correctIndex: 1, difficulty: 0.4, discrimination: 1.4, guessing: 0.25, tags: ['collaboration','consensus'] },
  { subTopic: 'Collaboration', text: 'A remote team member in a different time zone misses meetings. You:', options: [{index:0,text:'Complain to management without talking to them'},{index:1,text:'Talk to them directly to understand the issue and find a better meeting time'},{index:2,text:'Exclude them from meetings going forward'},{index:3,text:'Stop collaborating with them'}], correctIndex: 1, difficulty: 0.1, discrimination: 1.3, guessing: 0.25, tags: ['collaboration','remote'] },
  { subTopic: 'Collaboration', text: 'Your team has conflicting ideas about a solution. As a non-lead member, you should:', options: [{index:0,text:'Push only your idea and dismiss others'},{index:1,text:'Stay silent to avoid conflict'},{index:2,text:'Facilitate a structured discussion of trade-offs and help reach consensus'},{index:3,text:'Escalate to the manager to decide'}], correctIndex: 2, difficulty: 0.5, discrimination: 1.4, guessing: 0.25, tags: ['collaboration','facilitation'] },
  { subTopic: 'Collaboration', text: 'A colleague gives you incomplete handover notes before going on leave. You:', options: [{index:0,text:'Wait for them to return'},{index:1,text:'Complain to management'},{index:2,text:'Follow up with them before they leave and document what you learn'},{index:3,text:'Refuse to take on the work'}], correctIndex: 2, difficulty: 0.0, discrimination: 1.3, guessing: 0.25, tags: ['collaboration','handover'] },

  // ── Ownership & Initiative ────────────────────────────────────────────────
  { subTopic: 'Ownership', text: 'A bug in production is discovered. You didn\'t write the code, but you are on call. You:', options: [{index:0,text:'Wait for the original developer to fix it'},{index:1,text:'Take ownership, triage and fix or escalate immediately'},{index:2,text:'File a ticket and go to bed'},{index:3,text:'Tell the customer it will be fixed eventually'}], correctIndex: 1, difficulty: 0.3, discrimination: 1.5, guessing: 0.25, tags: ['ownership','incident'] },
  { subTopic: 'Ownership', text: 'Your manager is unavailable and a critical decision must be made. You:', options: [{index:0,text:'Make no decision and wait'},{index:1,text:'Make the best decision you can with available data, then inform your manager'},{index:2,text:'Escalate to a random colleague'},{index:3,text:'Make a decision but don\'t tell anyone'}], correctIndex: 1, difficulty: 0.6, discrimination: 1.4, guessing: 0.25, tags: ['ownership','initiative'] },
  { subTopic: 'Ownership', text: 'You identify a risk in a project outside your direct responsibility. You:', options: [{index:0,text:'Ignore it — not your problem'},{index:1,text:'Raise it with the appropriate person and offer to help mitigate'},{index:2,text:'Wait for it to become a problem'},{index:3,text:'Fix it without telling anyone'}], correctIndex: 1, difficulty: 0.1, discrimination: 1.4, guessing: 0.25, tags: ['ownership','proactivity'] },
  { subTopic: 'Ownership', text: 'A project you own is falling behind. The best action is:', options: [{index:0,text:'Say nothing until asked'},{index:1,text:'Proactively communicate the delay with a recovery plan'},{index:2,text:'Work nights without flagging the risk'},{index:3,text:'Blame external dependencies and wait'}], correctIndex: 1, difficulty: -0.1, discrimination: 1.4, guessing: 0.25, tags: ['ownership','communication'] },
  { subTopic: 'Ownership', text: 'After delivering a project, you receive no feedback. You:', options: [{index:0,text:'Assume everything was perfect'},{index:1,text:'Proactively request a retrospective to identify improvements'},{index:2,text:'Move on without reflection'},{index:3,text:'Complain that no one appreciated your work'}], correctIndex: 1, difficulty: 0.4, discrimination: 1.3, guessing: 0.25, tags: ['ownership','growth'] },

  // ── Professionalism ───────────────────────────────────────────────────────
  { subTopic: 'Professionalism', text: 'A client is rude to you on a call. You:', options: [{index:0,text:'Match their tone'},{index:1,text:'End the call immediately'},{index:2,text:'Stay calm, address their concern professionally, and document the interaction'},{index:3,text:'Complain about them on internal chat'}], correctIndex: 2, difficulty: 0.0, discrimination: 1.4, guessing: 0.25, tags: ['professionalism','communication'] },
  { subTopic: 'Professionalism', text: 'You are asked to attend a meeting you believe is unnecessary. You:', options: [{index:0,text:'Skip it without notice'},{index:1,text:'Attend and multitask visibly'},{index:2,text:'Politely clarify your role and offer to contribute asynchronously if attendance isn\'t critical'},{index:3,text:'Complain to your team about the culture'}], correctIndex: 2, difficulty: 0.5, discrimination: 1.3, guessing: 0.25, tags: ['professionalism','meetings'] },
  { subTopic: 'Professionalism', text: 'You are running late for a work commitment. You should:', options: [{index:0,text:'Just show up late'},{index:1,text:'Notify the relevant parties as soon as possible'},{index:2,text:'Send a message after you are already late'},{index:3,text:'Skip it entirely and reschedule'}], correctIndex: 1, difficulty: -0.7, discrimination: 1.3, guessing: 0.25, tags: ['professionalism','reliability'] },
  { subTopic: 'Professionalism', text: 'A colleague shares confidential project information in a public channel by mistake. You:', options: [{index:0,text:'Screenshot and share it further'},{index:1,text:'Ignore it'},{index:2,text:'Privately alert them and suggest they delete the post'},{index:3,text:'Forward it to your personal email for reference'}], correctIndex: 2, difficulty: 0.3, discrimination: 1.4, guessing: 0.25, tags: ['professionalism','confidentiality'] },
  { subTopic: 'Professionalism', text: 'You are asked to speak at an internal event but feel under-prepared. You:', options: [{index:0,text:'Cancel at the last minute'},{index:1,text:'Prepare adequately and ask for coaching if needed'},{index:2,text:'Go unprepared and wing it'},{index:3,text:'Send a written summary instead without informing organizers'}], correctIndex: 1, difficulty: 0.2, discrimination: 1.3, guessing: 0.25, tags: ['professionalism','communication'] },

  // ── Resilience ────────────────────────────────────────────────────────────
  { subTopic: 'Resilience', text: 'Your project gets cancelled after months of work. How do you respond?', options: [{index:0,text:'Express bitterness to management'},{index:1,text:'Accept the decision, document learnings, and channel energy into the next challenge'},{index:2,text:'Refuse new assignments'},{index:3,text:'Leave the company'}], correctIndex: 1, difficulty: 0.3, discrimination: 1.4, guessing: 0.25, tags: ['resilience'] },
  { subTopic: 'Resilience', text: 'You fail a certification exam. Your best response is:', options: [{index:0,text:'Give up on that skill area'},{index:1,text:'Analyze what went wrong, study the gaps, and retake it'},{index:2,text:'Blame the exam format'},{index:3,text:'Avoid mentioning it to your manager'}], correctIndex: 1, difficulty: -0.2, discrimination: 1.3, guessing: 0.25, tags: ['resilience','growth'] },
  { subTopic: 'Resilience', text: 'You experience a series of setbacks at work in a short time. The best strategy is:', options: [{index:0,text:'Isolate and handle everything alone'},{index:1,text:'Seek support from a mentor or manager and break challenges into smaller steps'},{index:2,text:'Request a transfer'},{index:3,text:'Take extended leave without a plan'}], correctIndex: 1, difficulty: 0.2, discrimination: 1.4, guessing: 0.25, tags: ['resilience','support'] },
  { subTopic: 'Resilience', text: 'Your solution is rejected after you invested significant effort. You:', options: [{index:0,text:'Argue that the reviewers are wrong'},{index:1,text:'Ask for specific feedback and use it to improve'},{index:2,text:'Ignore the feedback and resubmit unchanged'},{index:3,text:'Stop proposing solutions in the future'}], correctIndex: 1, difficulty: 0.1, discrimination: 1.4, guessing: 0.25, tags: ['resilience','feedback'] },
  { subTopic: 'Resilience', text: 'Under sustained high pressure, the healthiest response is:', options: [{index:0,text:'Push harder and ignore personal limits'},{index:1,text:'Communicate the pressure to your manager and implement sustainable practices'},{index:2,text:'Quietly reduce work quality'},{index:3,text:'Apply for other jobs immediately'}], correctIndex: 1, difficulty: 0.4, discrimination: 1.4, guessing: 0.25, tags: ['resilience','wellbeing'] },

  // ── Diversity & Inclusion ─────────────────────────────────────────────────
  { subTopic: 'Inclusion', text: 'A team member with a different cultural background communicates differently than you expect. You:', options: [{index:0,text:'Assume they are unprofessional'},{index:1,text:'Adapt your communication style and seek to understand their perspective'},{index:2,text:'Avoid interacting with them'},{index:3,text:'Report them to HR'}], correctIndex: 1, difficulty: 0.1, discrimination: 1.3, guessing: 0.25, tags: ['inclusion','diversity'] },
  { subTopic: 'Inclusion', text: 'You notice a qualified colleague is consistently overlooked in meetings. You:', options: [{index:0,text:'Ignore it'},{index:1,text:'Actively create space for them to contribute'},{index:2,text:'Tell them privately they need to be more assertive'},{index:3,text:'File an immediate formal complaint'}], correctIndex: 1, difficulty: 0.3, discrimination: 1.4, guessing: 0.25, tags: ['inclusion','allyship'] },
  { subTopic: 'Inclusion', text: 'A colleague makes an off-color joke in the workplace. You:', options: [{index:0,text:'Laugh along to avoid awkwardness'},{index:1,text:'Calmly address it in the moment or speak to them privately afterward'},{index:2,text:'Post about it on social media'},{index:3,text:'Never speak to them again'}], correctIndex: 1, difficulty: 0.4, discrimination: 1.4, guessing: 0.25, tags: ['inclusion','respect'] },
  { subTopic: 'Inclusion', text: 'When forming a project team, the best approach is:', options: [{index:0,text:'Choose only people you know well'},{index:1,text:'Intentionally include people with diverse skills, backgrounds, and perspectives'},{index:2,text:'Choose the fastest workers regardless of fit'},{index:3,text:'Let management assign people randomly'}], correctIndex: 1, difficulty: -0.1, discrimination: 1.3, guessing: 0.25, tags: ['inclusion','teambuilding'] },
  { subTopic: 'Inclusion', text: 'A team member discloses a disability that affects their work schedule. You:', options: [{index:0,text:'Suggest they find a different job'},{index:1,text:'Work with them and management to find reasonable accommodations'},{index:2,text:'Treat them the same as if they said nothing'},{index:3,text:'Share the information with the wider team'}], correctIndex: 1, difficulty: 0.2, discrimination: 1.4, guessing: 0.25, tags: ['inclusion','accessibility'] },

  // ── Continuous Learning ───────────────────────────────────────────────────
  { subTopic: 'Learning', text: 'Which approach best supports continuous learning in a professional role?', options: [{index:0,text:'Only learn when your manager tells you to'},{index:1,text:'Set personal learning goals aligned with business needs and track progress'},{index:2,text:'Take random online courses with no focus'},{index:3,text:'Rely solely on on-the-job experience'}], correctIndex: 1, difficulty: 0.2, discrimination: 1.3, guessing: 0.25, tags: ['learning','growth'] },
  { subTopic: 'Learning', text: 'You receive an opportunity to shadow a senior colleague. You:', options: [{index:0,text:'Decline — you are too busy'},{index:1,text:'Accept and prepare questions in advance to maximize learning'},{index:2,text:'Accept but stay passive throughout'},{index:3,text:'Ask them to teach you everything in one session'}], correctIndex: 1, difficulty: -0.3, discrimination: 1.3, guessing: 0.25, tags: ['learning','mentorship'] },
  { subTopic: 'Learning', text: 'A new technology becomes relevant to your role. You:', options: [{index:0,text:'Wait for mandatory training'},{index:1,text:'Self-initiate learning and apply it in a low-risk context'},{index:2,text:'Avoid using it since you weren\'t trained'},{index:3,text:'Tell your manager it is not needed'}], correctIndex: 1, difficulty: 0.0, discrimination: 1.4, guessing: 0.25, tags: ['learning','initiative'] },
  { subTopic: 'Learning', text: 'After completing a course, the best way to retain knowledge is:', options: [{index:0,text:'Re-read all notes immediately'},{index:1,text:'Apply the knowledge in a real or practice project'},{index:2,text:'Share the certificate on social media'},{index:3,text:'File the notes for future reference'}], correctIndex: 1, difficulty: 0.1, discrimination: 1.3, guessing: 0.25, tags: ['learning'] },
  { subTopic: 'Learning', text: 'Your company invests in your professional development. In return, the best approach is:', options: [{index:0,text:'Complete training and move on with no changes'},{index:1,text:'Apply learnings, share insights with peers, and contribute to a culture of growth'},{index:2,text:'Keep skills for personal career advancement only'},{index:3,text:'Demand more training before applying anything'}], correctIndex: 1, difficulty: 0.3, discrimination: 1.3, guessing: 0.25, tags: ['learning','culture'] },
];
