export const communicationQuestions = [
  // ── Written Communication ──────────────────────────────────────────────────
  { subTopic: 'Written', text: 'Which email opening is most professional?', options: [{index:0,text:'Hey!'},{index:1,text:'Dear Sir/Madam'},{index:2,text:'Dear [First Name],'},{index:3,text:'Yo team,'}], correctIndex: 2, difficulty: -0.8, discrimination: 1.2, guessing: 0.25, tags: ['written','email'] },
  { subTopic: 'Written', text: 'The "inverted pyramid" structure in business writing means:', options: [{index:0,text:'Building to the main point at the end'},{index:1,text:'Putting the most important information first'},{index:2,text:'Using bullet points throughout'},{index:3,text:'Starting with background context'}], correctIndex: 1, difficulty: 0.5, discrimination: 1.4, guessing: 0.25, tags: ['written','structure'] },
  { subTopic: 'Written', text: 'An executive summary should be:', options: [{index:0,text:'As long as the main document'},{index:1,text:'A technical deep-dive'},{index:2,text:'Concise, covering purpose, findings, and recommendations for decision-makers'},{index:3,text:'Written only after the report is approved'}], correctIndex: 2, difficulty: 0.3, discrimination: 1.4, guessing: 0.25, tags: ['written','business-writing'] },
  { subTopic: 'Written', text: 'Passive voice in professional writing should generally be:', options: [{index:0,text:'Used whenever possible for formality'},{index:1,text:'Minimized — active voice is clearer and more direct'},{index:2,text:'Required in all reports'},{index:3,text:'Used when the subject is known'}], correctIndex: 1, difficulty: 0.4, discrimination: 1.3, guessing: 0.25, tags: ['written','grammar'] },
  { subTopic: 'Written', text: 'When writing a proposal, the section that quantifies expected outcomes is called:', options: [{index:0,text:'Appendix'},{index:1,text:'Background'},{index:2,text:'Expected ROI / Business Case'},{index:3,text:'Table of Contents'}], correctIndex: 2, difficulty: 0.2, discrimination: 1.3, guessing: 0.25, tags: ['written','proposals'] },
  { subTopic: 'Written', text: 'The "so what?" test for business writing means:', options: [{index:0,text:'Asking if the format is correct'},{index:1,text:'Checking every statement answers why it matters to the reader'},{index:2,text:'Verifying spelling'},{index:3,text:'Confirming the word count is met'}], correctIndex: 1, difficulty: 0.6, discrimination: 1.4, guessing: 0.25, tags: ['written','clarity'] },
  { subTopic: 'Written', text: 'Which of these is the clearest sentence?', options: [{index:0,text:'The aforementioned considerations pertaining to the strategic initiative have been duly noted.'},{index:1,text:'We have noted your strategic concerns.'},{index:2,text:'In reference to that which was discussed...'},{index:3,text:'The matter has been regarded with due diligence.'}], correctIndex: 1, difficulty: 0.1, discrimination: 1.4, guessing: 0.25, tags: ['written','clarity'] },
  { subTopic: 'Written', text: 'When should you use bullet points vs prose in business writing?', options: [{index:0,text:'Always use bullets for speed'},{index:1,text:'Bullets for lists/steps; prose for narrative, analysis, and argument'},{index:2,text:'Prose is always more professional'},{index:3,text:'Bullets are informal — avoid them in documents'}], correctIndex: 1, difficulty: 0.4, discrimination: 1.4, guessing: 0.25, tags: ['written','formatting'] },
  { subTopic: 'Written', text: 'The BLUF principle in written communication stands for:', options: [{index:0,text:'Be Large, Underline, and Format'},{index:1,text:'Bottom Line Up Front — state the key point first'},{index:2,text:'Bullet Lists Under Format'},{index:3,text:'Brief Language Used Formally'}], correctIndex: 1, difficulty: 0.7, discrimination: 1.5, guessing: 0.25, tags: ['written','structure'] },
  { subTopic: 'Written', text: 'A status update email to stakeholders should include:', options: [{index:0,text:'Every detail of the work done'},{index:1,text:'Progress against plan, key decisions needed, blockers, and next steps'},{index:2,text:'Only good news to maintain morale'},{index:3,text:'Technical implementation details'}], correctIndex: 1, difficulty: 0.1, discrimination: 1.4, guessing: 0.25, tags: ['written','stakeholders'] },

  // ── Verbal Communication ───────────────────────────────────────────────────
  { subTopic: 'Verbal', text: 'In a presentation, the most effective way to open is:', options: [{index:0,text:'Recite the agenda in full'},{index:1,text:'Start with a compelling question, story, or data point that hooks the audience'},{index:2,text:'Apologize for any imperfections in advance'},{index:3,text:'Introduce all team members first'}], correctIndex: 1, difficulty: 0.3, discrimination: 1.4, guessing: 0.25, tags: ['verbal','presentations'] },
  { subTopic: 'Verbal', text: 'Paralanguage refers to:', options: [{index:0,text:'Speaking more than one language'},{index:1,text:'Non-verbal vocal cues such as tone, pace, pitch, and pausing'},{index:2,text:'Using technical jargon'},{index:3,text:'Translating between languages'}], correctIndex: 1, difficulty: 0.8, discrimination: 1.5, guessing: 0.25, tags: ['verbal','non-verbal'] },
  { subTopic: 'Verbal', text: 'When answering a question you don\'t know in a meeting, the best response is:', options: [{index:0,text:'Make up an answer confidently'},{index:1,text:'Say you don\'t know and commit to following up with the answer'},{index:2,text:'Deflect with another question'},{index:3,text:'Stay silent'}], correctIndex: 1, difficulty: -0.2, discrimination: 1.3, guessing: 0.25, tags: ['verbal','meetings'] },
  { subTopic: 'Verbal', text: 'Mirroring in communication means:', options: [{index:0,text:'Repeating everything the other person says'},{index:1,text:'Subtly matching someone\'s tone and body language to build rapport'},{index:2,text:'Contradicting their points'},{index:3,text:'Using the same words verbatim'}], correctIndex: 1, difficulty: 0.7, discrimination: 1.4, guessing: 0.25, tags: ['verbal','rapport'] },
  { subTopic: 'Verbal', text: 'To improve clarity when presenting complex information verbally, you should:', options: [{index:0,text:'Use as many technical terms as possible'},{index:1,text:'Structure with signposting: "First... Second... In summary..."'},{index:2,text:'Speak as fast as possible to fit everything in'},{index:3,text:'Avoid pausing as it shows uncertainty'}], correctIndex: 1, difficulty: 0.2, discrimination: 1.4, guessing: 0.25, tags: ['verbal','clarity'] },

  // ── Non-Verbal Communication ───────────────────────────────────────────────
  { subTopic: 'Non-Verbal', text: 'Eye contact in a professional conversation primarily conveys:', options: [{index:0,text:'Aggression'},{index:1,text:'Engagement, confidence, and trustworthiness'},{index:2,text:'Boredom'},{index:3,text:'Submission'}], correctIndex: 1, difficulty: -0.3, discrimination: 1.3, guessing: 0.25, tags: ['non-verbal','body-language'] },
  { subTopic: 'Non-Verbal', text: 'Crossed arms during a conversation typically signal:', options: [{index:0,text:'Openness to ideas'},{index:1,text:'Defensiveness or discomfort'},{index:2,text:'Deep thinking'},{index:3,text:'Enthusiasm'}], correctIndex: 1, difficulty: 0.1, discrimination: 1.3, guessing: 0.25, tags: ['non-verbal','body-language'] },
  { subTopic: 'Non-Verbal', text: 'Albert Mehrabian\'s research suggests that in face-to-face communication, words account for approximately:', options: [{index:0,text:'55% of the message'},{index:1,text:'38% of the message'},{index:2,text:'7% of the message'},{index:3,text:'20% of the message'}], correctIndex: 2, difficulty: 1.0, discrimination: 1.6, guessing: 0.25, tags: ['non-verbal','research'] },
  { subTopic: 'Non-Verbal', text: 'On a video call, leaning slightly forward suggests:', options: [{index:0,text:'Aggression'},{index:1,text:'Engagement and interest'},{index:2,text:'Disagreement'},{index:3,text:'Fatigue'}], correctIndex: 1, difficulty: 0.0, discrimination: 1.3, guessing: 0.25, tags: ['non-verbal','remote'] },
  { subTopic: 'Non-Verbal', text: 'Proxemics in communication refers to:', options: [{index:0,text:'The speed of speech'},{index:1,text:'The use and perception of physical space in social interaction'},{index:2,text:'Written formality level'},{index:3,text:'Eye movement patterns'}], correctIndex: 1, difficulty: 1.1, discrimination: 1.5, guessing: 0.25, tags: ['non-verbal','proxemics'] },

  // ── Intercultural Communication ────────────────────────────────────────────
  { subTopic: 'Intercultural', text: 'High-context cultures rely more on:', options: [{index:0,text:'Explicit written contracts'},{index:1,text:'Shared understanding, relationships, and implicit signals'},{index:2,text:'Direct verbal statements'},{index:3,text:'Formal documentation of every decision'}], correctIndex: 1, difficulty: 0.9, discrimination: 1.5, guessing: 0.25, tags: ['intercultural','cultural-dimensions'] },
  { subTopic: 'Intercultural', text: 'When communicating across cultures, the safest approach is:', options: [{index:0,text:'Assume your cultural norms apply universally'},{index:1,text:'Be curious, ask questions, observe, and adapt'},{index:2,text:'Avoid discussing cultural differences'},{index:3,text:'Rely on stereotypes for efficiency'}], correctIndex: 1, difficulty: -0.1, discrimination: 1.4, guessing: 0.25, tags: ['intercultural','adaptability'] },
  { subTopic: 'Intercultural', text: 'Power distance in Hofstede\'s model describes:', options: [{index:0,text:'Physical distance in office layouts'},{index:1,text:'The degree to which less powerful members accept unequal power distribution'},{index:2,text:'The hierarchy of communication channels'},{index:3,text:'The gap between senior and junior salaries'}], correctIndex: 1, difficulty: 1.2, discrimination: 1.6, guessing: 0.25, tags: ['intercultural','hofstede'] },
  { subTopic: 'Intercultural', text: 'Indirect communication is most associated with cultures that prioritize:', options: [{index:0,text:'Task completion speed'},{index:1,text:'Maintaining harmony and preserving face'},{index:2,text:'Legal precision'},{index:3,text:'Individual achievement'}], correctIndex: 1, difficulty: 0.8, discrimination: 1.5, guessing: 0.25, tags: ['intercultural','communication-styles'] },
  { subTopic: 'Intercultural', text: 'In a global virtual team, which practice best reduces miscommunication?', options: [{index:0,text:'Use idioms and informal language freely'},{index:1,text:'Confirm understanding explicitly and document decisions in writing'},{index:2,text:'Only communicate via video calls'},{index:3,text:'Assume everyone operates under the same work norms'}], correctIndex: 1, difficulty: 0.2, discrimination: 1.4, guessing: 0.25, tags: ['intercultural','virtual-teams'] },

  // ── Presentation Skills ───────────────────────────────────────────────────
  { subTopic: 'Presentations', text: 'The Minto Pyramid Principle for presentations recommends:', options: [{index:0,text:'Organizing slides alphabetically'},{index:1,text:'Starting with the conclusion, then supporting arguments and evidence'},{index:2,text:'Putting all data in the first slide'},{index:3,text:'Ending with the key recommendation'}], correctIndex: 1, difficulty: 0.9, discrimination: 1.5, guessing: 0.25, tags: ['presentations','structure'] },
  { subTopic: 'Presentations', text: 'The 10-20-30 rule (Guy Kawasaki) for presentations suggests:', options: [{index:0,text:'10 slides, 20 minutes, 30 pt minimum font'},{index:1,text:'10% visuals, 20% text, 30 second delivery'},{index:2,text:'10 points, 20 words per slide, 30 min max'},{index:3,text:'10 audience members, 20 slides, 30 min'}], correctIndex: 0, difficulty: 0.7, discrimination: 1.4, guessing: 0.25, tags: ['presentations','design'] },
  { subTopic: 'Presentations', text: 'When asked a hostile question during a presentation, you should:', options: [{index:0,text:'Respond emotionally to match their energy'},{index:1,text:'Stay calm, acknowledge the concern, and give a factual response'},{index:2,text:'Dismiss the question'},{index:3,text:'Ask the audience to move on'}], correctIndex: 1, difficulty: 0.3, discrimination: 1.4, guessing: 0.25, tags: ['presentations','Q&A'] },
  { subTopic: 'Presentations', text: 'Data visualization best practice for a business presentation:', options: [{index:0,text:'Include all available data points'},{index:1,text:'Choose the right chart type for the insight and remove chart junk'},{index:2,text:'Always use 3D charts for impact'},{index:3,text:'Add as much color as possible'}], correctIndex: 1, difficulty: 0.4, discrimination: 1.4, guessing: 0.25, tags: ['presentations','data-viz'] },
  { subTopic: 'Presentations', text: 'What is the "rule of three" in communication?', options: [{index:0,text:'Use three fonts per presentation'},{index:1,text:'Presenting ideas in groups of three is most memorable and persuasive'},{index:2,text:'A presentation should be no more than three minutes'},{index:3,text:'Ask the audience three questions'}], correctIndex: 1, difficulty: 0.5, discrimination: 1.4, guessing: 0.25, tags: ['presentations','rhetoric'] },

  // ── Listening Skills ──────────────────────────────────────────────────────
  { subTopic: 'Listening', text: 'Reflective listening involves:', options: [{index:0,text:'Taking notes silently'},{index:1,text:'Paraphrasing what you heard to confirm understanding'},{index:2,text:'Waiting for a pause to insert your point'},{index:3,text:'Agreeing with everything said'}], correctIndex: 1, difficulty: 0.2, discrimination: 1.4, guessing: 0.25, tags: ['listening','empathy'] },
  { subTopic: 'Listening', text: 'A major barrier to effective listening is:', options: [{index:0,text:'Taking too many notes'},{index:1,text:'Formulating your response while the other person is still speaking'},{index:2,text:'Maintaining eye contact'},{index:3,text:'Asking clarifying questions'}], correctIndex: 1, difficulty: 0.1, discrimination: 1.4, guessing: 0.25, tags: ['listening','barriers'] },
  { subTopic: 'Listening', text: 'Empathic listening prioritizes:', options: [{index:0,text:'Finding flaws in the argument'},{index:1,text:'Understanding the speaker\'s perspective and feelings, not just content'},{index:2,text:'Responding quickly'},{index:3,text:'Evaluating the logical structure'}], correctIndex: 1, difficulty: 0.4, discrimination: 1.4, guessing: 0.25, tags: ['listening','empathy'] },
  { subTopic: 'Listening', text: 'When someone is venting frustration, the best listening response is:', options: [{index:0,text:'Immediately offer solutions'},{index:1,text:'Acknowledge the feeling first before problem-solving'},{index:2,text:'Change the subject'},{index:3,text:'List reasons why they shouldn\'t feel that way'}], correctIndex: 1, difficulty: 0.3, discrimination: 1.4, guessing: 0.25, tags: ['listening','emotional'] },
  { subTopic: 'Listening', text: 'What does "listening to understand, not to reply" mean?', options: [{index:0,text:'Never replying to messages'},{index:1,text:'Giving full attention to meaning and intent rather than planning your next statement'},{index:2,text:'Understanding the topic before a meeting'},{index:3,text:'Reading between the lines for hidden agendas'}], correctIndex: 1, difficulty: 0.0, discrimination: 1.3, guessing: 0.25, tags: ['listening','mindfulness'] },

  // ── Feedback ─────────────────────────────────────────────────────────────
  { subTopic: 'Feedback', text: 'The SBI feedback model stands for:', options: [{index:0,text:'Situation, Behavior, Impact'},{index:1,text:'Specific, Brief, Impactful'},{index:2,text:'Start, Build, Improve'},{index:3,text:'Story, Behavior, Intention'}], correctIndex: 0, difficulty: 0.6, discrimination: 1.5, guessing: 0.25, tags: ['feedback','models'] },
  { subTopic: 'Feedback', text: 'The best time to give corrective feedback is:', options: [{index:0,text:'During the annual review'},{index:1,text:'As close to the event as possible, in private'},{index:2,text:'In front of the team to set an example'},{index:3,text:'Via email to create a paper trail'}], correctIndex: 1, difficulty: 0.2, discrimination: 1.4, guessing: 0.25, tags: ['feedback','timing'] },
  { subTopic: 'Feedback', text: 'The "feedback sandwich" technique involves:', options: [{index:0,text:'Mixing positive and negative feedback randomly'},{index:1,text:'Framing criticism between two pieces of positive feedback'},{index:2,text:'Giving three pieces of positive feedback per one criticism'},{index:3,text:'Sending feedback by email only'}], correctIndex: 1, difficulty: 0.3, discrimination: 1.3, guessing: 0.25, tags: ['feedback','techniques'] },
  { subTopic: 'Feedback', text: 'Receiving feedback well means:', options: [{index:0,text:'Agreeing with all feedback immediately'},{index:1,text:'Listening without interrupting, asking clarifying questions, and reflecting before responding'},{index:2,text:'Defending your position with data'},{index:3,text:'Thanking the person and ignoring it privately'}], correctIndex: 1, difficulty: 0.2, discrimination: 1.4, guessing: 0.25, tags: ['feedback','reception'] },
  { subTopic: 'Feedback', text: 'Positive reinforcement feedback is most effective when:', options: [{index:0,text:'Given at every interaction'},{index:1,text:'Specific, timely, and tied to observable behavior'},{index:2,text:'Delivered in group settings only'},{index:3,text:'Reserved for major achievements'}], correctIndex: 1, difficulty: 0.4, discrimination: 1.4, guessing: 0.25, tags: ['feedback','positive'] },

  // ── Digital Communication ──────────────────────────────────────────────────
  { subTopic: 'Digital', text: 'Netiquette in professional digital communication includes:', options: [{index:0,text:'Using all caps for emphasis'},{index:1,text:'Responding within expected timeframes and keeping messages concise and respectful'},{index:2,text:'CC-ing everyone on every email'},{index:3,text:'Using casual abbreviations freely'}], correctIndex: 1, difficulty: 0.1, discrimination: 1.3, guessing: 0.25, tags: ['digital','email'] },
  { subTopic: 'Digital', text: 'When should you pick up the phone instead of sending an email?', options: [{index:0,text:'Always — calls are more professional'},{index:1,text:'When the issue is urgent, complex, or emotionally sensitive'},{index:2,text:'Never — emails create a paper trail'},{index:3,text:'Only for external stakeholders'}], correctIndex: 1, difficulty: 0.3, discrimination: 1.4, guessing: 0.25, tags: ['digital','channel-selection'] },
  { subTopic: 'Digital', text: 'In a long email chain with many recipients, the best practice when making a decision is:', options: [{index:0,text:'Reply all with your decision'},{index:1,text:'Move to a direct conversation or small group, then distribute the decision'},{index:2,text:'Start a new email chain from scratch'},{index:3,text:'Post the decision in a shared document'}], correctIndex: 1, difficulty: 0.5, discrimination: 1.4, guessing: 0.25, tags: ['digital','email'] },
  { subTopic: 'Digital', text: 'The main risk of relying solely on asynchronous communication in a team is:', options: [{index:0,text:'Too many meetings'},{index:1,text:'Misalignment, delayed decisions, and loss of team cohesion'},{index:2,text:'Excessive documentation'},{index:3,text:'Privacy concerns'}], correctIndex: 1, difficulty: 0.6, discrimination: 1.4, guessing: 0.25, tags: ['digital','async'] },
  { subTopic: 'Digital', text: 'When sending a document for review, best practice is:', options: [{index:0,text:'Send it with no context'},{index:1,text:'Include a brief cover note with what you need, by when, and the key questions'},{index:2,text:'Attach all related documents as well'},{index:3,text:'Send reminders every hour'}], correctIndex: 1, difficulty: 0.0, discrimination: 1.3, guessing: 0.25, tags: ['digital','document'] },
];
