import { ForbiddenException, Injectable, NotFoundException, Scope } from '@nestjs/common';
import { REQUEST } from '@nestjs/core';
import { Inject } from '@nestjs/common';
import { PrismaService } from '../../database/prisma.service';
import { PermissionsService } from '../auth/permissions.service';
import { PERMISSIONS } from '../auth/permissions.constants';

interface ContributingAnswer {
  questionId: string;
  questionText: string;
  selectedOptionText: string | null;
  selectedOptionValue: number | null;
  timeTakenSec: number | null;
}

interface DimensionExplanation {
  dimension: string;
  score: number | null;
  contributingAnswers: ContributingAnswer[];
}

export interface ReportExplanation {
  reportId: string;
  narrative: string | null;
  recommendation: string | null;
  dimensionBreakdown: DimensionExplanation[];
  // Honest disclosure of the actual scoring mechanism, not a fabricated
  // feature-attribution claim: report-generator.service.ts scores via a
  // single LLM call that sees ALL submitted answers at once (not isolated
  // per-dimension), so "contributing answers" below are the ones tagged to
  // this dimension in the question bank, not a proven causal attribution —
  // the model had the full answer set as context for every dimension score.
  explanationMethod: string;
}

@Injectable({ scope: Scope.REQUEST })
export class ExplanationService {
  private tenantId: string;

  constructor(
    private prisma: PrismaService,
    private permissions: PermissionsService,
    @Inject(REQUEST) private request: any,
  ) {
    this.tenantId = request.headers['x-tenant-id'];
  }

  async explainReport(
    reportId: string,
    requesterFirebaseUid: string,
  ): Promise<ReportExplanation> {
    const requester = await this.permissions.resolveUser(requesterFirebaseUid, this.tenantId);
    if (!requester) {
      throw new NotFoundException('User not found');
    }

    const report = await this.prisma.aiReport.findFirst({
      where: { id: reportId, tenantId: this.tenantId },
      include: { session: true },
    });
    if (!report) {
      throw new NotFoundException('Report not found');
    }

    const isSelf = report.userId === requester.id;
    const canViewAny = this.permissions.hasPermission(requester, PERMISSIONS.REPORT_EXPLANATION_VIEW_ANY);
    if (!isSelf && !canViewAny) {
      throw new ForbiddenException(
        'Only the report subject or an org admin can view this explanation',
      );
    }

    // Enriched at submission time (assessment.service.ts submitAnswers) with
    // the real question text + selected option's meaning — no question-bank
    // lookup needed here. Sessions submitted before that enrichment existed
    // just show a placeholder rather than throwing.
    const answers = (report.session.answers ?? []) as Array<{
      questionId: string;
      selectedOptionId: string;
      timeTakenSec: number;
      dimensionId?: string | null;
      questionText?: string | null;
      selectedOptionText?: string | null;
      selectedOptionValue?: number | null;
    }>;
    const dimensionScores = (report.dimensionScores ?? {}) as Record<string, number>;

    const dimensionBreakdown: DimensionExplanation[] = Object.entries(dimensionScores).map(
      ([dimension, score]) => {
        const contributingAnswers = answers
          .filter((a) => a.dimensionId === dimension)
          .map((a) => ({
            questionId: a.questionId,
            questionText: a.questionText ?? '(question text unavailable for this submission)',
            selectedOptionText: a.selectedOptionText ?? null,
            selectedOptionValue: a.selectedOptionValue ?? null,
            timeTakenSec: a.timeTakenSec ?? null,
          }));
        return { dimension, score, contributingAnswers };
      },
    );

    return {
      reportId: report.id,
      narrative: report.narrative,
      recommendation: report.recommendation,
      dimensionBreakdown,
      explanationMethod:
        'Scores are generated by a single AI model call that evaluates all of your submitted ' +
        'answers together against every dimension at once, grounded in your answer data per the ' +
        'scoring prompt. The answers listed per dimension below are the ones tagged to that ' +
        'dimension in the question bank; the model had your full answer set as context when ' +
        'scoring every dimension, so this list identifies the most directly relevant answers, ' +
        'not an isolated mathematical weighting.',
    };
  }
}
