export const behavioralQuestions = [
  // ── Leadership ────────────────────────────────────────────────────────────
  { subTopic: 'Leadership', text: 'You are leading a team with two members in conflict. Using the STAR method, the best first action is:', options: [{index:0,text:'Let the conflict resolve itself'},{index:1,text:'Take sides with the higher performer'},{index:2,text:'Meet each party separately, then facilitate a structured conversation'},{index:3,text:'Immediately escalate to HR'}], correctIndex: 2, difficulty: 0.4, discrimination: 1.4, guessing: 0.25, tags: ['leadership','conflict'] },
  { subTopic: 'Leadership', text: 'A team member consistently underperforms. As their lead, you should:', options: [{index:0,text:'Document and fire them quickly'},{index:1,text:'Ignore it to avoid conflict'},{index:2,text:'Have a direct, compassionate performance conversation with clear expectations'},{index:3,text:'Reassign all their tasks'}], correctIndex: 2, difficulty: 0.5, discrimination: 1.5, guessing: 0.25, tags: ['leadership','performance'] },
  { subTopic: 'Leadership', text: 'You must motivate a team that has experienced repeated project cancellations. Your approach:', options: [{index:0,text:'Tell them the next project is guaranteed to ship'},{index:1,text:'Acknowledge the frustration, reconnect to purpose, and set achievable milestones'},{index:2,text:'Ignore morale and focus only on delivery'},{index:3,text:'Replace disengaged team members'}], correctIndex: 1, difficulty: 0.7, discrimination: 1.5, guessing: 0.25, tags: ['leadership','motivation'] },
  { subTopic: 'Leadership', text: 'A key stakeholder keeps changing requirements. You:', options: [{index:0,text:'Stop accepting new requirements'},{index:1,text:'Accept all changes without question'},{index:2,text:'Implement a change-control process and communicate impact of changes'},{index:3,text:'Deliver the original spec regardless'}], correctIndex: 2, difficulty: 0.6, discrimination: 1.4, guessing: 0.25, tags: ['leadership','stakeholders'] },
  { subTopic: 'Leadership', text: 'Your team delivers excellent results but receives no recognition from upper management. You:', options: [{index:0,text:'Tell the team it doesn\'t matter'},{index:1,text:'Advocate for recognition upward and celebrate internally within your team'},{index:2,text:'Complain to other managers'},{index:3,text:'Do nothing to avoid appearing self-promotional'}], correctIndex: 1, difficulty: 0.5, discrimination: 1.4, guessing: 0.25, tags: ['leadership','recognition'] },

  // ── Problem Solving ───────────────────────────────────────────────────────
  { subTopic: 'Problem Solving', text: 'A critical system goes down in production during peak hours. Your first step is:', options: [{index:0,text:'Start debugging without any communication'},{index:1,text:'Identify the blast radius, communicate status, then begin root cause analysis'},{index:2,text:'Reboot everything immediately'},{index:3,text:'Wait for someone else to fix it'}], correctIndex: 1, difficulty: 0.3, discrimination: 1.5, guessing: 0.25, tags: ['problem-solving','incident'] },
  { subTopic: 'Problem Solving', text: 'You are given a problem with insufficient information. You:', options: [{index:0,text:'Make assumptions and proceed silently'},{index:1,text:'State your assumptions explicitly, identify information gaps, and ask targeted questions'},{index:2,text:'Refuse to start until all information is available'},{index:3,text:'Deliver a solution to a different, better-defined problem'}], correctIndex: 1, difficulty: 0.4, discrimination: 1.5, guessing: 0.25, tags: ['problem-solving','ambiguity'] },
  { subTopic: 'Problem Solving', text: 'Multiple possible solutions exist for a problem. How do you choose?', options: [{index:0,text:'Choose the first one that comes to mind'},{index:1,text:'Choose the most complex to demonstrate skill'},{index:2,text:'Evaluate against criteria (speed, cost, risk, maintainability) and select the best fit'},{index:3,text:'Ask your manager to decide'}], correctIndex: 2, difficulty: 0.3, discrimination: 1.4, guessing: 0.25, tags: ['problem-solving','decision-making'] },
  { subTopic: 'Problem Solving', text: 'A solution you implemented caused unexpected side effects. You:', options: [{index:0,text:'Deny responsibility'},{index:1,text:'Revert, analyze the root cause, and design a safer fix'},{index:2,text:'Apply more patches on top'},{index:3,text:'Blame the requirements'}], correctIndex: 1, difficulty: 0.2, discrimination: 1.4, guessing: 0.25, tags: ['problem-solving','accountability'] },
  { subTopic: 'Problem Solving', text: 'You are stuck on a problem after an hour. What is the best next step?', options: [{index:0,text:'Keep trying the same approach'},{index:1,text:'Take a break, then try a different angle or ask a peer for input'},{index:2,text:'Give up and mark as blocked'},{index:3,text:'Escalate immediately to your manager'}], correctIndex: 1, difficulty: 0.1, discrimination: 1.3, guessing: 0.25, tags: ['problem-solving','creativity'] },

  // ── Communication ─────────────────────────────────────────────────────────
  { subTopic: 'Communication', text: 'You need to explain a complex technical issue to a non-technical stakeholder. You:', options: [{index:0,text:'Use all technical terms to appear credible'},{index:1,text:'Simplify with analogies, focus on business impact, and check for understanding'},{index:2,text:'Send a detailed technical document'},{index:3,text:'Delegate the conversation to a technical teammate'}], correctIndex: 1, difficulty: 0.2, discrimination: 1.4, guessing: 0.25, tags: ['communication','stakeholders'] },
  { subTopic: 'Communication', text: 'You send an email and receive no reply for 48 hours on an urgent matter. You:', options: [{index:0,text:'Send five more emails'},{index:1,text:'Call or message them on a different channel with a brief context reminder'},{index:2,text:'Assume they saw it and proceed without them'},{index:3,text:'Escalate to their manager immediately'}], correctIndex: 1, difficulty: 0.0, discrimination: 1.3, guessing: 0.25, tags: ['communication','follow-up'] },
  { subTopic: 'Communication', text: 'In a meeting, a colleague keeps interrupting others. As a peer, you:', options: [{index:0,text:'Interrupt them back louder'},{index:1,text:'Calmly redirect: "Let\'s hear [name] finish their thought"'},{index:2,text:'Say nothing'},{index:3,text:'Leave the meeting'}], correctIndex: 1, difficulty: 0.5, discrimination: 1.4, guessing: 0.25, tags: ['communication','meetings'] },
  { subTopic: 'Communication', text: 'You have bad news to deliver to a client. The best approach is:', options: [{index:0,text:'Delay sharing to see if it resolves itself'},{index:1,text:'Communicate early, explain clearly, and come with a plan'},{index:2,text:'Bury it in a long email'},{index:3,text:'Have a junior colleague deliver it'}], correctIndex: 1, difficulty: 0.1, discrimination: 1.5, guessing: 0.25, tags: ['communication','transparency'] },
  { subTopic: 'Communication', text: 'Active listening means:', options: [{index:0,text:'Waiting for your turn to speak'},{index:1,text:'Fully concentrating, understanding, and responding thoughtfully to what is said'},{index:2,text:'Taking notes on everything'},{index:3,text:'Repeating back exactly what was said'}], correctIndex: 1, difficulty: -0.2, discrimination: 1.3, guessing: 0.25, tags: ['communication','listening'] },

  // ── Decision Making ───────────────────────────────────────────────────────
  { subTopic: 'Decision Making', text: 'You must make a significant decision quickly with limited data. You:', options: [{index:0,text:'Wait until you have all the data'},{index:1,text:'Make the decision with available data, document assumptions, and plan to revisit'},{index:2,text:'Flip a coin'},{index:3,text:'Ask everyone and use the majority opinion'}], correctIndex: 1, difficulty: 0.6, discrimination: 1.5, guessing: 0.25, tags: ['decision-making','ambiguity'] },
  { subTopic: 'Decision Making', text: 'A decision you made turned out to be wrong. You:', options: [{index:0,text:'Defend the decision regardless'},{index:1,text:'Reverse course quickly, acknowledge the error, and share the lesson learned'},{index:2,text:'Blame incomplete information from others'},{index:3,text:'Quietly fix it without telling anyone'}], correctIndex: 1, difficulty: 0.3, discrimination: 1.4, guessing: 0.25, tags: ['decision-making','accountability'] },
  { subTopic: 'Decision Making', text: 'Which decision-making framework best manages cognitive bias?', options: [{index:0,text:'Going with gut instinct always'},{index:1,text:'Using structured analysis with explicit criteria and seeking dissenting views'},{index:2,text:'Delegating all decisions to avoid blame'},{index:3,text:'Following whatever was done last time'}], correctIndex: 1, difficulty: 0.8, discrimination: 1.5, guessing: 0.25, tags: ['decision-making','frameworks'] },
  { subTopic: 'Decision Making', text: 'Two equally valid paths exist for a project. How do you break the tie?', options: [{index:0,text:'Choose the cheaper option always'},{index:1,text:'Define the deciding criterion upfront (risk, reversibility, alignment) and apply it'},{index:2,text:'Let the team vote'},{index:3,text:'Choose the one your manager prefers without analysis'}], correctIndex: 1, difficulty: 0.7, discrimination: 1.5, guessing: 0.25, tags: ['decision-making'] },
  { subTopic: 'Decision Making', text: 'When should you escalate a decision rather than make it yourself?', options: [{index:0,text:'Always escalate every decision'},{index:1,text:'When the impact is beyond your authority, involves cross-functional trade-offs, or affects stakeholders you don\'t represent'},{index:2,text:'Never — always decide independently'},{index:3,text:'When you are unsure of the outcome'}], correctIndex: 1, difficulty: 0.5, discrimination: 1.5, guessing: 0.25, tags: ['decision-making','escalation'] },

  // ── Time Management ───────────────────────────────────────────────────────
  { subTopic: 'Time Management', text: 'You have five urgent tasks. The best first step is:', options: [{index:0,text:'Work on the most enjoyable task first'},{index:1,text:'Prioritize by impact and urgency, then communicate your plan'},{index:2,text:'Do all simultaneously'},{index:3,text:'Ask someone else to take all five'}], correctIndex: 1, difficulty: -0.3, discrimination: 1.3, guessing: 0.25, tags: ['time-management','prioritization'] },
  { subTopic: 'Time Management', text: 'You consistently miss self-set deadlines. The root cause is most likely:', options: [{index:0,text:'Too many meetings'},{index:1,text:'Poor estimation, unclear priorities, or failure to protect focused work time'},{index:2,text:'Unhelpful colleagues'},{index:3,text:'Bad tools'}], correctIndex: 1, difficulty: 0.4, discrimination: 1.4, guessing: 0.25, tags: ['time-management','self-awareness'] },
  { subTopic: 'Time Management', text: 'Which technique helps reduce context switching?', options: [{index:0,text:'Checking email every 5 minutes'},{index:1,text:'Batching similar tasks and protecting deep work blocks'},{index:2,text:'Attending every meeting to stay informed'},{index:3,text:'Starting multiple tasks at once'}], correctIndex: 1, difficulty: 0.3, discrimination: 1.4, guessing: 0.25, tags: ['time-management','productivity'] },
  { subTopic: 'Time Management', text: 'You are working on a high-priority task when an urgent but low-impact request comes in. You:', options: [{index:0,text:'Stop your work immediately for the request'},{index:1,text:'Evaluate true urgency, schedule it if possible, and protect current work'},{index:2,text:'Ignore the request entirely'},{index:3,text:'Hand the request to a colleague without checking their capacity'}], correctIndex: 1, difficulty: 0.2, discrimination: 1.4, guessing: 0.25, tags: ['time-management','prioritization'] },
  { subTopic: 'Time Management', text: 'The Eisenhower Matrix classifies tasks by:', options: [{index:0,text:'Difficulty and time required'},{index:1,text:'Urgency and importance'},{index:2,text:'Team size and budget'},{index:3,text:'Risk and complexity'}], correctIndex: 1, difficulty: 0.5, discrimination: 1.4, guessing: 0.25, tags: ['time-management','frameworks'] },

  // ── Negotiation & Influence ───────────────────────────────────────────────
  { subTopic: 'Negotiation', text: 'You need to convince a skeptical stakeholder to support your proposal. Your approach:', options: [{index:0,text:'Assert authority'},{index:1,text:'Understand their concerns, frame the proposal around their goals, and use data'},{index:2,text:'Escalate over their head'},{index:3,text:'Repeat your position more forcefully'}], correctIndex: 1, difficulty: 0.6, discrimination: 1.5, guessing: 0.25, tags: ['negotiation','influence'] },
  { subTopic: 'Negotiation', text: 'In a negotiation, the BATNA concept means:', options: [{index:0,text:'Best Alternative To a Negotiated Agreement — your walkaway position'},{index:1,text:'A negotiation scripting tool'},{index:2,text:'Best Approach To Negotiate Amicably'},{index:3,text:'A pricing framework'}], correctIndex: 0, difficulty: 1.0, discrimination: 1.6, guessing: 0.25, tags: ['negotiation','frameworks'] },
  { subTopic: 'Negotiation', text: 'Principled negotiation focuses on:', options: [{index:0,text:'Winning at all costs'},{index:1,text:'Positions, not interests'},{index:2,text:'Interests, not positions, and mutual gains where possible'},{index:3,text:'Avoiding negotiation entirely'}], correctIndex: 2, difficulty: 0.9, discrimination: 1.5, guessing: 0.25, tags: ['negotiation','frameworks'] },
  { subTopic: 'Negotiation', text: 'A vendor quotes a price 40% above budget. Your first move is:', options: [{index:0,text:'Reject immediately'},{index:1,text:'Accept to avoid conflict'},{index:2,text:'Understand the breakdown, share your constraints, and explore trade-offs'},{index:3,text:'Find a different vendor without informing them'}], correctIndex: 2, difficulty: 0.5, discrimination: 1.4, guessing: 0.25, tags: ['negotiation','vendor'] },
  { subTopic: 'Negotiation', text: 'When should you use silence as a negotiation tactic?', options: [{index:0,text:'Never — always fill silence'},{index:1,text:'After making an offer, to let the other party respond without prompting'},{index:2,text:'To signal aggression'},{index:3,text:'Only when you have nothing to say'}], correctIndex: 1, difficulty: 0.8, discrimination: 1.5, guessing: 0.25, tags: ['negotiation','tactics'] },

  // ── Customer Focus ────────────────────────────────────────────────────────
  { subTopic: 'Customer Focus', text: 'A customer complains that a product doesn\'t meet their expectations. Your first step:', options: [{index:0,text:'Explain why their expectations are wrong'},{index:1,text:'Listen fully, acknowledge their frustration, and ask clarifying questions'},{index:2,text:'Offer a refund immediately without investigation'},{index:3,text:'Transfer them to another department'}], correctIndex: 1, difficulty: -0.1, discrimination: 1.4, guessing: 0.25, tags: ['customer-focus','empathy'] },
  { subTopic: 'Customer Focus', text: 'Building long-term customer relationships is best achieved by:', options: [{index:0,text:'Maximizing each transaction value'},{index:1,text:'Consistently delivering on promises and proactively sharing relevant insights'},{index:2,text:'Never saying no to any request'},{index:3,text:'Sending frequent promotional emails'}], correctIndex: 1, difficulty: 0.2, discrimination: 1.4, guessing: 0.25, tags: ['customer-focus','relationship'] },
  { subTopic: 'Customer Focus', text: 'A customer requests a feature that is technically feasible but doesn\'t align with product strategy. You:', options: [{index:0,text:'Promise it immediately'},{index:1,text:'Acknowledge the need, explain the strategy, and offer alternatives'},{index:2,text:'Ignore the request'},{index:3,text:'Implement it without consulting the product team'}], correctIndex: 1, difficulty: 0.5, discrimination: 1.4, guessing: 0.25, tags: ['customer-focus','product'] },
  { subTopic: 'Customer Focus', text: 'Net Promoter Score (NPS) measures:', options: [{index:0,text:'Transaction volume'},{index:1,text:'The likelihood of customers recommending your product to others'},{index:2,text:'Customer service call duration'},{index:3,text:'Product feature usage'}], correctIndex: 1, difficulty: 0.3, discrimination: 1.3, guessing: 0.25, tags: ['customer-focus','metrics'] },
  { subTopic: 'Customer Focus', text: 'Customer effort score (CES) is important because:', options: [{index:0,text:'High effort predicts satisfaction'},{index:1,text:'Reducing customer effort strongly correlates with loyalty and repurchase'},{index:2,text:'It measures product quality directly'},{index:3,text:'It tracks the number of support tickets'}], correctIndex: 1, difficulty: 0.9, discrimination: 1.5, guessing: 0.25, tags: ['customer-focus','metrics'] },

  // ── Coaching & Mentoring ──────────────────────────────────────────────────
  { subTopic: 'Coaching', text: 'A mentee is struggling to reach their goals. The most effective coaching approach is:', options: [{index:0,text:'Tell them exactly what to do'},{index:1,text:'Ask powerful questions to help them identify their own path forward'},{index:2,text:'Take over their tasks'},{index:3,text:'Reduce their goals to make them easier'}], correctIndex: 1, difficulty: 0.6, discrimination: 1.5, guessing: 0.25, tags: ['coaching','leadership'] },
  { subTopic: 'Coaching', text: 'The GROW coaching model stands for:', options: [{index:0,text:'Goal, Reality, Options, Will'},{index:1,text:'Growth, Reflection, Outcome, Wisdom'},{index:2,text:'Guide, Reflect, Observe, Win'},{index:3,text:'Goal, Resources, Outcome, Work'}], correctIndex: 0, difficulty: 1.0, discrimination: 1.5, guessing: 0.25, tags: ['coaching','frameworks'] },
  { subTopic: 'Coaching', text: 'When giving developmental feedback, the most effective structure is:', options: [{index:0,text:'Only highlight positives to build confidence'},{index:1,text:'Be specific about behaviors, their impact, and desired change'},{index:2,text:'Compare the person to their peers'},{index:3,text:'Deliver feedback through email only'}], correctIndex: 1, difficulty: 0.4, discrimination: 1.4, guessing: 0.25, tags: ['coaching','feedback'] },
  { subTopic: 'Coaching', text: 'A team member rejects your feedback. You:', options: [{index:0,text:'Withdraw the feedback to avoid conflict'},{index:1,text:'Understand their perspective, restate the observable behavior and impact, and stay curious'},{index:2,text:'Escalate to HR immediately'},{index:3,text:'Repeat the feedback more forcefully'}], correctIndex: 1, difficulty: 0.7, discrimination: 1.5, guessing: 0.25, tags: ['coaching','feedback'] },
  { subTopic: 'Coaching', text: 'Psychological safety in a team means:', options: [{index:0,text:'Everyone always agrees'},{index:1,text:'Team members feel safe to speak up, take risks, and make mistakes without fear of punishment'},{index:2,text:'No one is ever held accountable'},{index:3,text:'All decisions are made by consensus'}], correctIndex: 1, difficulty: 0.5, discrimination: 1.5, guessing: 0.25, tags: ['coaching','teamwork'] },
];
