export const psychometricQuestions = [
  // ── Abstract Reasoning ────────────────────────────────────────────────────
  { subTopic: 'Abstract Reasoning', text: 'Sequence: 2, 4, 8, 16, ? — What is the next number?', options: [{index:0,text:'24'},{index:1,text:'32'},{index:2,text:'30'},{index:3,text:'18'}], correctIndex: 1, difficulty: -0.8, discrimination: 1.4, guessing: 0.25, tags: ['abstract','sequences'] },
  { subTopic: 'Abstract Reasoning', text: 'Which shape completes the pattern: △ □ △ □ △ ?', options: [{index:0,text:'△'},{index:1,text:'□'},{index:2,text:'○'},{index:3,text:'◇'}], correctIndex: 1, difficulty: -1.0, discrimination: 1.5, guessing: 0.25, tags: ['abstract','patterns'] },
  { subTopic: 'Abstract Reasoning', text: 'Sequence: 1, 1, 2, 3, 5, 8, ? — What is next?', options: [{index:0,text:'12'},{index:1,text:'11'},{index:2,text:'13'},{index:3,text:'10'}], correctIndex: 2, difficulty: 0.0, discrimination: 1.5, guessing: 0.25, tags: ['abstract','fibonacci'] },
  { subTopic: 'Abstract Reasoning', text: 'If all Bloops are Razzles and all Razzles are Lazzles, then:', options: [{index:0,text:'Some Bloops are not Lazzles'},{index:1,text:'All Bloops are Lazzles'},{index:2,text:'All Lazzles are Bloops'},{index:3,text:'No Bloops are Lazzles'}], correctIndex: 1, difficulty: 0.3, discrimination: 1.5, guessing: 0.25, tags: ['abstract','logic'] },
  { subTopic: 'Abstract Reasoning', text: 'Sequence: 3, 6, 12, 24, ? — What is next?', options: [{index:0,text:'36'},{index:1,text:'48'},{index:2,text:'30'},{index:3,text:'42'}], correctIndex: 1, difficulty: -0.5, discrimination: 1.4, guessing: 0.25, tags: ['abstract','sequences'] },
  { subTopic: 'Abstract Reasoning', text: 'What is the odd one out: 27, 64, 100, 125, 216?', options: [{index:0,text:'27'},{index:1,text:'64'},{index:2,text:'100'},{index:3,text:'216'}], correctIndex: 2, difficulty: 0.8, discrimination: 1.6, guessing: 0.25, tags: ['abstract','number-series'] },
  { subTopic: 'Abstract Reasoning', text: 'Sequence: 100, 90, 81, 73, 66, ? — What is next?', options: [{index:0,text:'62'},{index:1,text:'60'},{index:2,text:'58'},{index:3,text:'55'}], correctIndex: 1, difficulty: 1.0, discrimination: 1.6, guessing: 0.25, tags: ['abstract','sequences'] },
  { subTopic: 'Abstract Reasoning', text: 'If MANGO → 13-1-14-7-15, what does 3-1-20 represent?', options: [{index:0,text:'CAR'},{index:1,text:'BAT'},{index:2,text:'CAT'},{index:3,text:'DOG'}], correctIndex: 2, difficulty: 0.4, discrimination: 1.4, guessing: 0.25, tags: ['abstract','coding'] },
  { subTopic: 'Abstract Reasoning', text: 'A pattern increases by +3, +5, +7, +9... Starting from 2, the 5th term is:', options: [{index:0,text:'22'},{index:1,text:'26'},{index:2,text:'24'},{index:3,text:'28'}], correctIndex: 1, difficulty: 0.9, discrimination: 1.5, guessing: 0.25, tags: ['abstract','sequences'] },
  { subTopic: 'Abstract Reasoning', text: 'Which number replaces the "?" — 4:16 :: 7:?', options: [{index:0,text:'28'},{index:1,text:'49'},{index:2,text:'21'},{index:3,text:'14'}], correctIndex: 1, difficulty: -0.3, discrimination: 1.5, guessing: 0.25, tags: ['abstract','analogies'] },

  // ── Numerical Reasoning ───────────────────────────────────────────────────
  { subTopic: 'Numerical Reasoning', text: 'A product costs $80 after a 20% discount. What was the original price?', options: [{index:0,text:'$96'},{index:1,text:'$100'},{index:2,text:'$104'},{index:3,text:'$98'}], correctIndex: 1, difficulty: 0.1, discrimination: 1.4, guessing: 0.25, tags: ['numerical','percentages'] },
  { subTopic: 'Numerical Reasoning', text: 'If 12 workers complete a task in 8 days, how many days would 16 workers take?', options: [{index:0,text:'5 days'},{index:1,text:'6 days'},{index:2,text:'7 days'},{index:3,text:'4 days'}], correctIndex: 1, difficulty: 0.5, discrimination: 1.5, guessing: 0.25, tags: ['numerical','work-rate'] },
  { subTopic: 'Numerical Reasoning', text: 'Revenue grew from $2.4M to $3.6M. What is the percentage increase?', options: [{index:0,text:'40%'},{index:1,text:'50%'},{index:2,text:'33%'},{index:3,text:'60%'}], correctIndex: 1, difficulty: 0.3, discrimination: 1.4, guessing: 0.25, tags: ['numerical','percentages'] },
  { subTopic: 'Numerical Reasoning', text: 'A train travels at 90 km/h. How far does it travel in 40 minutes?', options: [{index:0,text:'54 km'},{index:1,text:'60 km'},{index:2,text:'45 km'},{index:3,text:'72 km'}], correctIndex: 1, difficulty: 0.4, discrimination: 1.4, guessing: 0.25, tags: ['numerical','speed-distance'] },
  { subTopic: 'Numerical Reasoning', text: 'What is 15% of 340?', options: [{index:0,text:'48'},{index:1,text:'51'},{index:2,text:'54'},{index:3,text:'45'}], correctIndex: 1, difficulty: -0.4, discrimination: 1.3, guessing: 0.25, tags: ['numerical','percentages'] },
  { subTopic: 'Numerical Reasoning', text: 'If 3x + 7 = 22, what is x?', options: [{index:0,text:'4'},{index:1,text:'5'},{index:2,text:'6'},{index:3,text:'3'}], correctIndex: 1, difficulty: -0.6, discrimination: 1.4, guessing: 0.25, tags: ['numerical','algebra'] },
  { subTopic: 'Numerical Reasoning', text: 'A pie chart shows sales split: East 35%, West 25%, North 20%, South ?%. What is South?', options: [{index:0,text:'15%'},{index:1,text:'20%'},{index:2,text:'25%'},{index:3,text:'10%'}], correctIndex: 1, difficulty: -0.5, discrimination: 1.3, guessing: 0.25, tags: ['numerical','data-interpretation'] },
  { subTopic: 'Numerical Reasoning', text: 'Q1 sales: $120K, Q2: $144K. What was the Q1-Q2 growth rate?', options: [{index:0,text:'16.7%'},{index:1,text:'20%'},{index:2,text:'24%'},{index:3,text:'18%'}], correctIndex: 1, difficulty: 0.2, discrimination: 1.4, guessing: 0.25, tags: ['numerical','growth-rate'] },
  { subTopic: 'Numerical Reasoning', text: 'A company has a current ratio of 2.5. Current liabilities are $400K. Current assets are:', options: [{index:0,text:'$800K'},{index:1,text:'$1,000K'},{index:2,text:'$600K'},{index:3,text:'$900K'}], correctIndex: 1, difficulty: 0.7, discrimination: 1.5, guessing: 0.25, tags: ['numerical','finance'] },
  { subTopic: 'Numerical Reasoning', text: 'CAGR formula — a company grows from $500K to $1.62M in 5 years. What is the approximate CAGR?', options: [{index:0,text:'20%'},{index:1,text:'26%'},{index:2,text:'30%'},{index:3,text:'15%'}], correctIndex: 1, difficulty: 1.2, discrimination: 1.6, guessing: 0.25, tags: ['numerical','finance'] },

  // ── Verbal Reasoning ──────────────────────────────────────────────────────
  { subTopic: 'Verbal Reasoning', text: 'EPHEMERAL most nearly means:', options: [{index:0,text:'Eternal'},{index:1,text:'Short-lived'},{index:2,text:'Transparent'},{index:3,text:'Consequential'}], correctIndex: 1, difficulty: 0.6, discrimination: 1.4, guessing: 0.25, tags: ['verbal','vocabulary'] },
  { subTopic: 'Verbal Reasoning', text: 'LUCID most nearly means:', options: [{index:0,text:'Opaque'},{index:1,text:'Clear and easy to understand'},{index:2,text:'Flexible'},{index:3,text:'Complicated'}], correctIndex: 1, difficulty: 0.2, discrimination: 1.3, guessing: 0.25, tags: ['verbal','vocabulary'] },
  { subTopic: 'Verbal Reasoning', text: 'AMALGAMATE most nearly means:', options: [{index:0,text:'Separate'},{index:1,text:'Combine'},{index:2,text:'Accelerate'},{index:3,text:'Distribute'}], correctIndex: 1, difficulty: 0.5, discrimination: 1.4, guessing: 0.25, tags: ['verbal','vocabulary'] },
  { subTopic: 'Verbal Reasoning', text: 'PRAGMATIC most nearly means:', options: [{index:0,text:'Idealistic'},{index:1,text:'Practical and focused on results'},{index:2,text:'Theoretical'},{index:3,text:'Emotional'}], correctIndex: 1, difficulty: 0.1, discrimination: 1.3, guessing: 0.25, tags: ['verbal','vocabulary'] },
  { subTopic: 'Verbal Reasoning', text: 'PERFIDIOUS most nearly means:', options: [{index:0,text:'Loyal'},{index:1,text:'Treacherous'},{index:2,text:'Ambitious'},{index:3,text:'Cautious'}], correctIndex: 1, difficulty: 1.0, discrimination: 1.5, guessing: 0.25, tags: ['verbal','vocabulary'] },

  // ── Logical Reasoning ─────────────────────────────────────────────────────
  { subTopic: 'Logical Reasoning', text: 'All managers attend the Monday meeting. Sarah did not attend Monday\'s meeting. Therefore:', options: [{index:0,text:'Sarah is a manager who was sick'},{index:1,text:'Sarah is not a manager'},{index:2,text:'Sarah forgot the meeting'},{index:3,text:'The meeting was cancelled'}], correctIndex: 1, difficulty: -0.2, discrimination: 1.5, guessing: 0.25, tags: ['logical','deduction'] },
  { subTopic: 'Logical Reasoning', text: 'Some A are B. All B are C. Which must be true?', options: [{index:0,text:'All A are C'},{index:1,text:'Some A are C'},{index:2,text:'All C are A'},{index:3,text:'No A are C'}], correctIndex: 1, difficulty: 0.5, discrimination: 1.6, guessing: 0.25, tags: ['logical','syllogism'] },
  { subTopic: 'Logical Reasoning', text: 'If it rains, the match is cancelled. The match was not cancelled. Therefore:', options: [{index:0,text:'It did not rain'},{index:1,text:'It rained but play continued'},{index:2,text:'The match was postponed'},{index:3,text:'Cannot be determined'}], correctIndex: 0, difficulty: 0.3, discrimination: 1.5, guessing: 0.25, tags: ['logical','contrapositive'] },
  { subTopic: 'Logical Reasoning', text: 'Which of these is a logical fallacy: "Everyone is buying this product, so it must be good"?', options: [{index:0,text:'Straw man'},{index:1,text:'Ad hominem'},{index:2,text:'Bandwagon / Appeal to popularity'},{index:3,text:'False dichotomy'}], correctIndex: 2, difficulty: 0.8, discrimination: 1.5, guessing: 0.25, tags: ['logical','fallacies'] },
  { subTopic: 'Logical Reasoning', text: 'A → B, B → C, therefore:', options: [{index:0,text:'C → A'},{index:1,text:'A → C'},{index:2,text:'C → B'},{index:3,text:'B → A'}], correctIndex: 1, difficulty: 0.1, discrimination: 1.5, guessing: 0.25, tags: ['logical','transitivity'] },
  { subTopic: 'Logical Reasoning', text: 'Only employees with badges enter the building. Tom entered the building. Therefore:', options: [{index:0,text:'Tom has a badge'},{index:1,text:'Tom is an employee'},{index:2,text:'Tom has a badge — but may not be an employee'},{index:3,text:'Tom is a manager'}], correctIndex: 2, difficulty: 0.9, discrimination: 1.6, guessing: 0.25, tags: ['logical','deduction'] },
  { subTopic: 'Logical Reasoning', text: 'Which of these statements is NOT a valid logical conclusion from "If P then Q, P is true"?', options: [{index:0,text:'Q is true'},{index:1,text:'P is a sufficient condition for Q'},{index:2,text:'Q being true means P is true'},{index:3,text:'Both P and Q are true'}], correctIndex: 2, difficulty: 1.1, discrimination: 1.6, guessing: 0.25, tags: ['logical','conditionals'] },

  // ── Spatial Reasoning ─────────────────────────────────────────────────────
  { subTopic: 'Spatial Reasoning', text: 'A cube has 6 faces. How many edges does it have?', options: [{index:0,text:'8'},{index:1,text:'12'},{index:2,text:'10'},{index:3,text:'6'}], correctIndex: 1, difficulty: 0.0, discrimination: 1.3, guessing: 0.25, tags: ['spatial','geometry'] },
  { subTopic: 'Spatial Reasoning', text: 'If you fold a piece of paper in half 3 times, how many layers result?', options: [{index:0,text:'6'},{index:1,text:'8'},{index:2,text:'9'},{index:3,text:'12'}], correctIndex: 1, difficulty: 0.4, discrimination: 1.4, guessing: 0.25, tags: ['spatial','3d'] },
  { subTopic: 'Spatial Reasoning', text: 'A square is rotated 45°. What shape does it appear to be?', options: [{index:0,text:'Circle'},{index:1,text:'Diamond / Rhombus'},{index:2,text:'Rectangle'},{index:3,text:'Triangle'}], correctIndex: 1, difficulty: -0.3, discrimination: 1.3, guessing: 0.25, tags: ['spatial','rotation'] },
  { subTopic: 'Spatial Reasoning', text: 'How many faces does a triangular prism have?', options: [{index:0,text:'4'},{index:1,text:'5'},{index:2,text:'6'},{index:3,text:'3'}], correctIndex: 1, difficulty: 0.3, discrimination: 1.4, guessing: 0.25, tags: ['spatial','3d'] },
  { subTopic: 'Spatial Reasoning', text: 'You are facing North and turn 270° clockwise. Which direction are you now facing?', options: [{index:0,text:'South'},{index:1,text:'East'},{index:2,text:'West'},{index:3,text:'North'}], correctIndex: 2, difficulty: 0.6, discrimination: 1.5, guessing: 0.25, tags: ['spatial','directions'] },

  // ── Emotional Intelligence ─────────────────────────────────────────────────
  { subTopic: 'Emotional Intelligence', text: 'The four domains of emotional intelligence (Goleman) are:', options: [{index:0,text:'IQ, EQ, SQ, AQ'},{index:1,text:'Self-awareness, Self-management, Social awareness, Relationship management'},{index:2,text:'Logic, Empathy, Drive, Control'},{index:3,text:'Intuition, Reflection, Analysis, Action'}], correctIndex: 1, difficulty: 0.7, discrimination: 1.5, guessing: 0.25, tags: ['eq','frameworks'] },
  { subTopic: 'Emotional Intelligence', text: 'Self-awareness in EQ means:', options: [{index:0,text:'Knowing your job description well'},{index:1,text:'Accurately recognizing your own emotions and their impact on others'},{index:2,text:'Memorizing your team\'s preferences'},{index:3,text:'Avoiding emotional reactions entirely'}], correctIndex: 1, difficulty: 0.2, discrimination: 1.4, guessing: 0.25, tags: ['eq','self-awareness'] },
  { subTopic: 'Emotional Intelligence', text: 'Empathy in a professional context means:', options: [{index:0,text:'Agreeing with everything colleagues say'},{index:1,text:'Understanding and sharing the feelings of others to inform better decisions'},{index:2,text:'Taking responsibility for others\' emotions'},{index:3,text:'Expressing emotions openly at all times'}], correctIndex: 1, difficulty: 0.3, discrimination: 1.4, guessing: 0.25, tags: ['eq','empathy'] },
  { subTopic: 'Emotional Intelligence', text: 'Emotional regulation under stress is best described as:', options: [{index:0,text:'Suppressing all emotions'},{index:1,text:'Recognizing emotional triggers and choosing measured responses'},{index:2,text:'Expressing every emotion immediately'},{index:3,text:'Avoiding stressful situations entirely'}], correctIndex: 1, difficulty: 0.5, discrimination: 1.4, guessing: 0.25, tags: ['eq','regulation'] },
  { subTopic: 'Emotional Intelligence', text: 'Social intelligence involves:', options: [{index:0,text:'Having a large professional network'},{index:1,text:'Reading social cues and navigating social situations effectively'},{index:2,text:'Being extroverted'},{index:3,text:'Knowing people\'s names and birthdays'}], correctIndex: 1, difficulty: 0.6, discrimination: 1.4, guessing: 0.25, tags: ['eq','social'] },

  // ── Critical Thinking ─────────────────────────────────────────────────────
  { subTopic: 'Critical Thinking', text: 'Confirmation bias means:', options: [{index:0,text:'Trusting only numbers'},{index:1,text:'Seeking evidence that confirms existing beliefs while discounting contradictory information'},{index:2,text:'Being overly cautious'},{index:3,text:'Relying on a single expert opinion'}], correctIndex: 1, difficulty: 0.5, discrimination: 1.5, guessing: 0.25, tags: ['critical-thinking','bias'] },
  { subTopic: 'Critical Thinking', text: 'Correlation vs causation: two trends moving together means:', options: [{index:0,text:'One causes the other'},{index:1,text:'They may be related but causation requires further evidence'},{index:2,text:'Both are caused by the same factor'},{index:3,text:'They are unrelated'}], correctIndex: 1, difficulty: 0.4, discrimination: 1.5, guessing: 0.25, tags: ['critical-thinking','statistics'] },
  { subTopic: 'Critical Thinking', text: 'The first step in evaluating a data-driven claim is:', options: [{index:0,text:'Accept it if from a credible source'},{index:1,text:'Check the sample size, methodology, and potential conflicts of interest'},{index:2,text:'Share it widely if it supports your view'},{index:3,text:'Reject it if it contradicts common belief'}], correctIndex: 1, difficulty: 0.6, discrimination: 1.5, guessing: 0.25, tags: ['critical-thinking','data'] },
  { subTopic: 'Critical Thinking', text: 'A first-principles thinker solves problems by:', options: [{index:0,text:'Copying best practices from competitors'},{index:1,text:'Breaking a problem to its fundamental truths and building up from there'},{index:2,text:'Applying the most common solution'},{index:3,text:'Using analogies from other industries'}], correctIndex: 1, difficulty: 0.8, discrimination: 1.5, guessing: 0.25, tags: ['critical-thinking','frameworks'] },
  { subTopic: 'Critical Thinking', text: 'The 5 Whys technique is used to:', options: [{index:0,text:'Generate five options for a decision'},{index:1,text:'Identify the root cause of a problem by repeatedly asking "why"'},{index:2,text:'Evaluate five stakeholder perspectives'},{index:3,text:'Rank risks by severity'}], correctIndex: 1, difficulty: 0.3, discrimination: 1.4, guessing: 0.25, tags: ['critical-thinking','problem-solving'] },
];
