export const technicalQuestions = [
  // ── Algorithms & Data Structures ──────────────────────────────────────────
  { subTopic: 'Algorithms', text: 'What is the average time complexity of QuickSort?', options: [{index:0,text:'O(n²)'},{index:1,text:'O(n log n)'},{index:2,text:'O(n)'},{index:3,text:'O(log n)'}], correctIndex: 1, difficulty: 0.2, discrimination: 1.4, guessing: 0.25, tags: ['algorithms','sorting'] },
  { subTopic: 'Algorithms', text: 'Which data structure uses LIFO ordering?', options: [{index:0,text:'Queue'},{index:1,text:'Heap'},{index:2,text:'Stack'},{index:3,text:'Deque'}], correctIndex: 2, difficulty: -1.0, discrimination: 1.2, guessing: 0.25, tags: ['data-structures'] },
  { subTopic: 'Algorithms', text: 'What is the time complexity of binary search?', options: [{index:0,text:'O(n)'},{index:1,text:'O(log n)'},{index:2,text:'O(n log n)'},{index:3,text:'O(1)'}], correctIndex: 1, difficulty: -0.8, discrimination: 1.3, guessing: 0.25, tags: ['algorithms','search'] },
  { subTopic: 'Algorithms', text: 'Which sorting algorithm has the best worst-case time complexity?', options: [{index:0,text:'QuickSort'},{index:1,text:'BubbleSort'},{index:2,text:'MergeSort'},{index:3,text:'SelectionSort'}], correctIndex: 2, difficulty: 0.4, discrimination: 1.5, guessing: 0.25, tags: ['algorithms','sorting'] },
  { subTopic: 'Algorithms', text: 'What does a hash table use to handle collisions in chaining?', options: [{index:0,text:'Arrays'},{index:1,text:'Linked lists'},{index:2,text:'Trees'},{index:3,text:'Stacks'}], correctIndex: 1, difficulty: 0.3, discrimination: 1.3, guessing: 0.25, tags: ['data-structures','hash'] },
  { subTopic: 'Algorithms', text: 'What is the space complexity of Depth First Search on a graph with V vertices and E edges?', options: [{index:0,text:'O(V+E)'},{index:1,text:'O(E)'},{index:2,text:'O(V)'},{index:3,text:'O(1)'}], correctIndex: 2, difficulty: 0.8, discrimination: 1.4, guessing: 0.25, tags: ['algorithms','graphs'] },
  { subTopic: 'Algorithms', text: 'In a min-heap, the root node contains:', options: [{index:0,text:'The maximum value'},{index:1,text:'The minimum value'},{index:2,text:'A random value'},{index:3,text:'The median value'}], correctIndex: 1, difficulty: -0.5, discrimination: 1.3, guessing: 0.25, tags: ['data-structures','heap'] },
  { subTopic: 'Algorithms', text: 'Dijkstra\'s algorithm cannot handle:', options: [{index:0,text:'Directed graphs'},{index:1,text:'Undirected graphs'},{index:2,text:'Negative edge weights'},{index:3,text:'Disconnected graphs'}], correctIndex: 2, difficulty: 0.9, discrimination: 1.5, guessing: 0.25, tags: ['algorithms','graphs'] },
  { subTopic: 'Algorithms', text: 'Which traversal visits nodes level by level?', options: [{index:0,text:'In-order'},{index:1,text:'Pre-order'},{index:2,text:'Post-order'},{index:3,text:'BFS / Level-order'}], correctIndex: 3, difficulty: 0.1, discrimination: 1.4, guessing: 0.25, tags: ['trees','traversal'] },
  { subTopic: 'Algorithms', text: 'What is the amortized time complexity of a dynamic array append operation?', options: [{index:0,text:'O(n)'},{index:1,text:'O(log n)'},{index:2,text:'O(1)'},{index:3,text:'O(n²)'}], correctIndex: 2, difficulty: 1.1, discrimination: 1.6, guessing: 0.25, tags: ['data-structures','amortized'] },

  // ── JavaScript ───────────────────────────────────────────────────────────
  { subTopic: 'JavaScript', text: 'What does `typeof null` return in JavaScript?', options: [{index:0,text:'"null"'},{index:1,text:'"undefined"'},{index:2,text:'"object"'},{index:3,text:'"boolean"'}], correctIndex: 2, difficulty: 0.6, discrimination: 1.4, guessing: 0.25, tags: ['javascript','quirks'] },
  { subTopic: 'JavaScript', text: 'Which method creates a shallow copy of an array?', options: [{index:0,text:'arr.copy()'},{index:1,text:'arr.slice()'},{index:2,text:'arr.clone()'},{index:3,text:'arr.splice()'}], correctIndex: 1, difficulty: 0.0, discrimination: 1.3, guessing: 0.25, tags: ['javascript','arrays'] },
  { subTopic: 'JavaScript', text: 'What is a closure in JavaScript?', options: [{index:0,text:'A function with no return value'},{index:1,text:'A function that retains access to its outer scope after the outer function returns'},{index:2,text:'An immediately invoked function'},{index:3,text:'A method on an object'}], correctIndex: 1, difficulty: 0.5, discrimination: 1.5, guessing: 0.25, tags: ['javascript','closures'] },
  { subTopic: 'JavaScript', text: 'What does the `===` operator check?', options: [{index:0,text:'Value only'},{index:1,text:'Type only'},{index:2,text:'Value and type'},{index:3,text:'Reference equality'}], correctIndex: 2, difficulty: -0.9, discrimination: 1.5, guessing: 0.25, tags: ['javascript','operators'] },
  { subTopic: 'JavaScript', text: 'What is the output of `0.1 + 0.2 === 0.3` in JavaScript?', options: [{index:0,text:'true'},{index:1,text:'false'},{index:2,text:'undefined'},{index:3,text:'NaN'}], correctIndex: 1, difficulty: 0.7, discrimination: 1.4, guessing: 0.25, tags: ['javascript','floating-point'] },
  { subTopic: 'JavaScript', text: 'Which keyword creates a block-scoped variable?', options: [{index:0,text:'var'},{index:1,text:'let'},{index:2,text:'function'},{index:3,text:'global'}], correctIndex: 1, difficulty: -0.7, discrimination: 1.3, guessing: 0.25, tags: ['javascript','scope'] },
  { subTopic: 'JavaScript', text: 'What is event delegation?', options: [{index:0,text:'Passing events between components'},{index:1,text:'Using a parent element to handle events from children via bubbling'},{index:2,text:'Triggering events programmatically'},{index:3,text:'Preventing default event behavior'}], correctIndex: 1, difficulty: 0.8, discrimination: 1.4, guessing: 0.25, tags: ['javascript','dom','events'] },
  { subTopic: 'JavaScript', text: 'What does `Promise.all` do when one promise rejects?', options: [{index:0,text:'Waits for all to settle'},{index:1,text:'Resolves with partial results'},{index:2,text:'Rejects immediately'},{index:3,text:'Ignores the rejection'}], correctIndex: 2, difficulty: 0.4, discrimination: 1.5, guessing: 0.25, tags: ['javascript','promises'] },
  { subTopic: 'JavaScript', text: 'What is the prototype chain in JavaScript?', options: [{index:0,text:'A list of parent classes'},{index:1,text:'A mechanism for objects to inherit properties from other objects'},{index:2,text:'The call stack'},{index:3,text:'A chain of promises'}], correctIndex: 1, difficulty: 0.9, discrimination: 1.5, guessing: 0.25, tags: ['javascript','prototypes'] },
  { subTopic: 'JavaScript', text: 'What does `Array.prototype.reduce` do?', options: [{index:0,text:'Filters array elements'},{index:1,text:'Maps each element to a new value'},{index:2,text:'Executes a reducer function to produce a single value'},{index:3,text:'Sorts the array'}], correctIndex: 2, difficulty: 0.3, discrimination: 1.3, guessing: 0.25, tags: ['javascript','functional'] },

  // ── TypeScript ───────────────────────────────────────────────────────────
  { subTopic: 'TypeScript', text: 'What is the `unknown` type in TypeScript?', options: [{index:0,text:'Equivalent to `any`'},{index:1,text:'A type-safe counterpart to `any` that requires type-checking before use'},{index:2,text:'An alias for `undefined`'},{index:3,text:'The type of unresolved promises'}], correctIndex: 1, difficulty: 1.0, discrimination: 1.6, guessing: 0.25, tags: ['typescript'] },
  { subTopic: 'TypeScript', text: 'What does the `readonly` modifier do?', options: [{index:0,text:'Prevents the variable from being logged'},{index:1,text:'Makes a property immutable after initialization'},{index:2,text:'Makes a property private'},{index:3,text:'Converts a class to abstract'}], correctIndex: 1, difficulty: 0.2, discrimination: 1.4, guessing: 0.25, tags: ['typescript'] },
  { subTopic: 'TypeScript', text: 'What is a TypeScript generic?', options: [{index:0,text:'A template string'},{index:1,text:'A type that works with any type when instantiated'},{index:2,text:'A utility for JSON parsing'},{index:3,text:'A decorator'}], correctIndex: 1, difficulty: 0.5, discrimination: 1.5, guessing: 0.25, tags: ['typescript','generics'] },
  { subTopic: 'TypeScript', text: 'What does `interface` vs `type` differ in TypeScript?', options: [{index:0,text:'No difference'},{index:1,text:'Interfaces can be extended/merged; types support unions and mapped types more flexibly'},{index:2,text:'Types compile to classes'},{index:3,text:'Interfaces cannot be used with generics'}], correctIndex: 1, difficulty: 1.1, discrimination: 1.6, guessing: 0.25, tags: ['typescript'] },
  { subTopic: 'TypeScript', text: 'What is the `Partial<T>` utility type?', options: [{index:0,text:'Makes all properties required'},{index:1,text:'Makes all properties optional'},{index:2,text:'Removes all properties'},{index:3,text:'Makes all properties readonly'}], correctIndex: 1, difficulty: 0.3, discrimination: 1.4, guessing: 0.25, tags: ['typescript','utility-types'] },

  // ── System Design ────────────────────────────────────────────────────────
  { subTopic: 'System Design', text: 'What does CAP theorem state?', options: [{index:0,text:'Consistency, Availability, and Partition tolerance cannot all be guaranteed simultaneously'},{index:1,text:'Systems must have Consistency, Atomicity, and Performance'},{index:2,text:'Cache, API, and Protocol are required for distributed systems'},{index:3,text:'Concurrency, Availability, and Persistence are trade-offs'}], correctIndex: 0, difficulty: 1.2, discrimination: 1.4, guessing: 0.25, tags: ['system-design','distributed'] },
  { subTopic: 'System Design', text: 'What is horizontal scaling?', options: [{index:0,text:'Increasing CPU/RAM of a single server'},{index:1,text:'Adding more machines to a pool'},{index:2,text:'Partitioning a database vertically'},{index:3,text:'Caching responses at the CDN'}], correctIndex: 1, difficulty: 0.0, discrimination: 1.3, guessing: 0.25, tags: ['system-design','scalability'] },
  { subTopic: 'System Design', text: 'What is a CDN used for?', options: [{index:0,text:'Database replication'},{index:1,text:'Serving static assets from geographically distributed servers closer to the user'},{index:2,text:'Load balancing between microservices'},{index:3,text:'Encrypting API traffic'}], correctIndex: 1, difficulty: -0.3, discrimination: 1.3, guessing: 0.25, tags: ['system-design','cdn'] },
  { subTopic: 'System Design', text: 'What is the purpose of a message queue like Kafka?', options: [{index:0,text:'Storing relational data'},{index:1,text:'Decoupling producers from consumers and buffering high-throughput events'},{index:2,text:'Caching API responses'},{index:3,text:'Load balancing HTTP requests'}], correctIndex: 1, difficulty: 0.9, discrimination: 1.5, guessing: 0.25, tags: ['system-design','messaging'] },
  { subTopic: 'System Design', text: 'What is database sharding?', options: [{index:0,text:'Encrypting database columns'},{index:1,text:'Creating read replicas'},{index:2,text:'Horizontally partitioning data across multiple databases'},{index:3,text:'Backing up a database to object storage'}], correctIndex: 2, difficulty: 1.0, discrimination: 1.5, guessing: 0.25, tags: ['system-design','databases'] },
  { subTopic: 'System Design', text: 'What is the difference between SQL and NoSQL databases?', options: [{index:0,text:'SQL is faster; NoSQL is slower'},{index:1,text:'SQL uses structured schemas with ACID; NoSQL is schema-flexible and trades consistency for scale'},{index:2,text:'NoSQL supports joins; SQL does not'},{index:3,text:'SQL runs in memory; NoSQL on disk'}], correctIndex: 1, difficulty: 0.4, discrimination: 1.4, guessing: 0.25, tags: ['system-design','databases'] },
  { subTopic: 'System Design', text: 'What is an API Gateway?', options: [{index:0,text:'A physical network router'},{index:1,text:'A single entry point that routes, authenticates, and rate-limits requests to microservices'},{index:2,text:'A REST client library'},{index:3,text:'A type of load balancer for TCP traffic'}], correctIndex: 1, difficulty: 0.6, discrimination: 1.4, guessing: 0.25, tags: ['system-design','microservices'] },

  // ── Databases ────────────────────────────────────────────────────────────
  { subTopic: 'Databases', text: 'What does ACID stand for in database transactions?', options: [{index:0,text:'Atomicity, Consistency, Isolation, Durability'},{index:1,text:'Availability, Consistency, Isolation, Distribution'},{index:2,text:'Atomicity, Concurrency, Integrity, Distribution'},{index:3,text:'Availability, Concurrency, Isolation, Durability'}], correctIndex: 0, difficulty: 0.6, discrimination: 1.5, guessing: 0.25, tags: ['databases','transactions'] },
  { subTopic: 'Databases', text: 'What is a database index used for?', options: [{index:0,text:'Enforcing foreign key constraints'},{index:1,text:'Encrypting sensitive columns'},{index:2,text:'Speeding up read queries at the cost of write overhead'},{index:3,text:'Backing up table data'}], correctIndex: 2, difficulty: 0.1, discrimination: 1.4, guessing: 0.25, tags: ['databases','performance'] },
  { subTopic: 'Databases', text: 'What is a LEFT JOIN?', options: [{index:0,text:'Returns only matching rows from both tables'},{index:1,text:'Returns all rows from the left table and matched rows from the right'},{index:2,text:'Returns only rows from the right table'},{index:3,text:'Joins tables on primary keys only'}], correctIndex: 1, difficulty: 0.0, discrimination: 1.3, guessing: 0.25, tags: ['databases','sql'] },
  { subTopic: 'Databases', text: 'What is database normalization?', options: [{index:0,text:'Encrypting data at rest'},{index:1,text:'Organizing data to reduce redundancy and improve integrity'},{index:2,text:'Distributing data across shards'},{index:3,text:'Creating full-text search indexes'}], correctIndex: 1, difficulty: 0.3, discrimination: 1.4, guessing: 0.25, tags: ['databases','modeling'] },
  { subTopic: 'Databases', text: 'What is a deadlock in database terms?', options: [{index:0,text:'A query that takes too long'},{index:1,text:'Two or more transactions waiting on each other\'s locks indefinitely'},{index:2,text:'A corrupted index'},{index:3,text:'A failed migration'}], correctIndex: 1, difficulty: 0.8, discrimination: 1.5, guessing: 0.25, tags: ['databases','concurrency'] },

  // ── Networking ───────────────────────────────────────────────────────────
  { subTopic: 'Networking', text: 'What is the difference between TCP and UDP?', options: [{index:0,text:'TCP is faster; UDP is reliable'},{index:1,text:'TCP is connection-oriented and reliable; UDP is connectionless and faster but unreliable'},{index:2,text:'UDP is encrypted; TCP is not'},{index:3,text:'TCP is for UDP traffic only'}], correctIndex: 1, difficulty: 0.3, discrimination: 1.4, guessing: 0.25, tags: ['networking'] },
  { subTopic: 'Networking', text: 'What does HTTP status code 429 mean?', options: [{index:0,text:'Not Found'},{index:1,text:'Internal Server Error'},{index:2,text:'Too Many Requests'},{index:3,text:'Unauthorized'}], correctIndex: 2, difficulty: 0.5, discrimination: 1.3, guessing: 0.25, tags: ['networking','http'] },
  { subTopic: 'Networking', text: 'What is TLS used for?', options: [{index:0,text:'Compressing HTTP responses'},{index:1,text:'Encrypting data in transit between client and server'},{index:2,text:'Authenticating users'},{index:3,text:'Caching DNS responses'}], correctIndex: 1, difficulty: 0.1, discrimination: 1.4, guessing: 0.25, tags: ['networking','security'] },
  { subTopic: 'Networking', text: 'What is a REST API?', options: [{index:0,text:'A binary protocol for microservices'},{index:1,text:'An architectural style using HTTP methods and stateless communication'},{index:2,text:'A database query language'},{index:3,text:'A type of WebSocket connection'}], correctIndex: 1, difficulty: -0.5, discrimination: 1.3, guessing: 0.25, tags: ['networking','api'] },
  { subTopic: 'Networking', text: 'What is a WebSocket?', options: [{index:0,text:'A secure HTTP method'},{index:1,text:'A protocol providing full-duplex communication over a single TCP connection'},{index:2,text:'A type of REST endpoint'},{index:3,text:'A DNS record type'}], correctIndex: 1, difficulty: 0.6, discrimination: 1.4, guessing: 0.25, tags: ['networking','realtime'] },

  // ── Security ─────────────────────────────────────────────────────────────
  { subTopic: 'Security', text: 'What is SQL injection?', options: [{index:0,text:'Inserting SQL comments'},{index:1,text:'Embedding malicious SQL in user input to manipulate queries'},{index:2,text:'Encrypting SQL queries'},{index:3,text:'A type of database index'}], correctIndex: 1, difficulty: 0.0, discrimination: 1.4, guessing: 0.25, tags: ['security','owasp'] },
  { subTopic: 'Security', text: 'What is a JWT (JSON Web Token)?', options: [{index:0,text:'A database record format'},{index:1,text:'An encrypted database column'},{index:2,text:'A compact, self-contained token for transmitting claims as a JSON object'},{index:3,text:'A hashing algorithm'}], correctIndex: 2, difficulty: 0.4, discrimination: 1.4, guessing: 0.25, tags: ['security','auth'] },
  { subTopic: 'Security', text: 'What does XSS stand for?', options: [{index:0,text:'External Style Sheets'},{index:1,text:'Cross-Site Scripting'},{index:2,text:'Cross-Server Sessions'},{index:3,text:'Extensible Security Schema'}], correctIndex: 1, difficulty: 0.2, discrimination: 1.3, guessing: 0.25, tags: ['security','owasp'] },
  { subTopic: 'Security', text: 'What is bcrypt used for?', options: [{index:0,text:'Encrypting API payloads'},{index:1,text:'Hashing passwords with a built-in salt and work factor'},{index:2,text:'Signing JWT tokens'},{index:3,text:'Generating UUIDs'}], correctIndex: 1, difficulty: 0.5, discrimination: 1.5, guessing: 0.25, tags: ['security','cryptography'] },
  { subTopic: 'Security', text: 'What is CORS?', options: [{index:0,text:'A type of SQL query'},{index:1,text:'A browser mechanism that restricts cross-origin HTTP requests'},{index:2,text:'A certificate standard'},{index:3,text:'A network load balancer protocol'}], correctIndex: 1, difficulty: 0.6, discrimination: 1.4, guessing: 0.25, tags: ['security','web'] },

  // ── DevOps / Cloud ───────────────────────────────────────────────────────
  { subTopic: 'DevOps', text: 'What is a Docker container?', options: [{index:0,text:'A virtual machine'},{index:1,text:'A lightweight, portable, isolated runtime environment'},{index:2,text:'A type of cloud function'},{index:3,text:'A network proxy'}], correctIndex: 1, difficulty: -0.2, discrimination: 1.3, guessing: 0.25, tags: ['devops','docker'] },
  { subTopic: 'DevOps', text: 'What does CI/CD stand for?', options: [{index:0,text:'Container Isolation / Container Deployment'},{index:1,text:'Continuous Integration / Continuous Delivery'},{index:2,text:'Code Inspection / Code Distribution'},{index:3,text:'Cluster Integration / Cluster Deployment'}], correctIndex: 1, difficulty: -0.3, discrimination: 1.3, guessing: 0.25, tags: ['devops','cicd'] },
  { subTopic: 'DevOps', text: 'What is Kubernetes used for?', options: [{index:0,text:'Writing SQL queries'},{index:1,text:'Orchestrating containerized applications across a cluster'},{index:2,text:'Running unit tests'},{index:3,text:'Encrypting secrets at rest'}], correctIndex: 1, difficulty: 0.5, discrimination: 1.4, guessing: 0.25, tags: ['devops','kubernetes'] },
  { subTopic: 'DevOps', text: 'What is Infrastructure as Code (IaC)?', options: [{index:0,text:'Writing application code in cloud IDEs'},{index:1,text:'Provisioning and managing infrastructure using machine-readable config files'},{index:2,text:'Running code on bare-metal servers'},{index:3,text:'Automating UI testing'}], correctIndex: 1, difficulty: 0.7, discrimination: 1.4, guessing: 0.25, tags: ['devops','iac'] },
  { subTopic: 'DevOps', text: 'What is the purpose of environment variables in deployments?', options: [{index:0,text:'Speeding up build times'},{index:1,text:'Separating configuration from code for portability and security'},{index:2,text:'Storing database schemas'},{index:3,text:'Encrypting log files'}], correctIndex: 1, difficulty: 0.1, discrimination: 1.3, guessing: 0.25, tags: ['devops','config'] },

  // ── React & Frontend ─────────────────────────────────────────────────────
  { subTopic: 'React', text: 'What is the virtual DOM?', options: [{index:0,text:'A separate browser process'},{index:1,text:'A lightweight in-memory representation of the real DOM used to batch updates'},{index:2,text:'A CSS-in-JS solution'},{index:3,text:'A server-side rendering technique'}], correctIndex: 1, difficulty: 0.3, discrimination: 1.4, guessing: 0.25, tags: ['react','frontend'] },
  { subTopic: 'React', text: 'When does `useEffect` run with an empty dependency array?', options: [{index:0,text:'Every render'},{index:1,text:'Only when state changes'},{index:2,text:'Once after the first render (mount)'},{index:3,text:'Before every render'}], correctIndex: 2, difficulty: 0.2, discrimination: 1.4, guessing: 0.25, tags: ['react','hooks'] },
  { subTopic: 'React', text: 'What is the purpose of `React.memo`?', options: [{index:0,text:'To manage global state'},{index:1,text:'To prevent re-renders when props have not changed'},{index:2,text:'To handle side effects'},{index:3,text:'To lazy-load components'}], correctIndex: 1, difficulty: 0.6, discrimination: 1.5, guessing: 0.25, tags: ['react','performance'] },
  { subTopic: 'React', text: 'What is prop drilling?', options: [{index:0,text:'A performance optimization'},{index:1,text:'Passing props through many layers of components that don\'t need them'},{index:2,text:'A Redux pattern'},{index:3,text:'A way to update state from child to parent'}], correctIndex: 1, difficulty: 0.4, discrimination: 1.3, guessing: 0.25, tags: ['react','patterns'] },
  { subTopic: 'React', text: 'What does `useMemo` do?', options: [{index:0,text:'Caches a function reference between renders'},{index:1,text:'Manages side effects'},{index:2,text:'Memoizes a computed value to avoid expensive recalculations on every render'},{index:3,text:'Creates a ref to a DOM element'}], correctIndex: 2, difficulty: 0.7, discrimination: 1.5, guessing: 0.25, tags: ['react','hooks','performance'] },

  // ── Computer Science Fundamentals ─────────────────────────────────────────
  { subTopic: 'CS Fundamentals', text: 'What is tail recursion?', options: [{index:0,text:'Recursion with no base case'},{index:1,text:'Recursion where the recursive call is the last operation, enabling stack optimization'},{index:2,text:'Looping backwards through an array'},{index:3,text:'Recursion using two functions'}], correctIndex: 1, difficulty: 1.1, discrimination: 1.6, guessing: 0.25, tags: ['cs','recursion'] },
  { subTopic: 'CS Fundamentals', text: 'What is Big-O notation used for?', options: [{index:0,text:'Measuring memory in bits'},{index:1,text:'Describing the upper bound of an algorithm\'s growth rate'},{index:2,text:'Representing binary numbers'},{index:3,text:'Specifying data types'}], correctIndex: 1, difficulty: -0.4, discrimination: 1.4, guessing: 0.25, tags: ['cs','complexity'] },
  { subTopic: 'CS Fundamentals', text: 'What is a race condition?', options: [{index:0,text:'A fast database query'},{index:1,text:'A situation where program behavior depends on non-deterministic timing of concurrent events'},{index:2,text:'Two servers racing to respond first'},{index:3,text:'A CPU benchmark metric'}], correctIndex: 1, difficulty: 0.9, discrimination: 1.5, guessing: 0.25, tags: ['cs','concurrency'] },
  { subTopic: 'CS Fundamentals', text: 'What is memoization?', options: [{index:0,text:'A sorting technique'},{index:1,text:'Caching results of expensive function calls to avoid recomputation'},{index:2,text:'Deleting unused memory'},{index:3,text:'Compiling code ahead of time'}], correctIndex: 1, difficulty: 0.5, discrimination: 1.4, guessing: 0.25, tags: ['cs','optimization'] },
  { subTopic: 'CS Fundamentals', text: 'What is the difference between a process and a thread?', options: [{index:0,text:'No difference in modern OS'},{index:1,text:'A process is an independent program with its own memory; threads share the process memory'},{index:2,text:'A thread runs on multiple CPUs; a process on one'},{index:3,text:'Processes are faster than threads'}], correctIndex: 1, difficulty: 0.7, discrimination: 1.5, guessing: 0.25, tags: ['cs','os'] },

  // ── Design Patterns ───────────────────────────────────────────────────────
  { subTopic: 'Design Patterns', text: 'What is the Singleton pattern?', options: [{index:0,text:'A pattern that creates a new instance for each request'},{index:1,text:'A pattern ensuring a class has only one instance and provides a global access point'},{index:2,text:'A pattern for composing objects'},{index:3,text:'A pattern for asynchronous operations'}], correctIndex: 1, difficulty: 0.3, discrimination: 1.4, guessing: 0.25, tags: ['design-patterns'] },
  { subTopic: 'Design Patterns', text: 'What does the Observer pattern do?', options: [{index:0,text:'Observes CPU usage'},{index:1,text:'Defines a one-to-many dependency so that state changes notify all dependents'},{index:2,text:'Wraps legacy code'},{index:3,text:'Manages database connections'}], correctIndex: 1, difficulty: 0.5, discrimination: 1.5, guessing: 0.25, tags: ['design-patterns'] },
  { subTopic: 'Design Patterns', text: 'What is the Factory pattern?', options: [{index:0,text:'A pattern for managing state'},{index:1,text:'A pattern that defines an interface for creating objects without specifying their concrete classes'},{index:2,text:'A structural pattern for wrapping APIs'},{index:3,text:'A pattern for caching'}], correctIndex: 1, difficulty: 0.4, discrimination: 1.4, guessing: 0.25, tags: ['design-patterns'] },
  { subTopic: 'Design Patterns', text: 'What is Dependency Injection?', options: [{index:0,text:'Importing modules at runtime'},{index:1,text:'A technique where dependencies are passed to a class rather than created inside it'},{index:2,text:'A pattern for lazy loading'},{index:3,text:'Injecting SQL into queries'}], correctIndex: 1, difficulty: 0.8, discrimination: 1.5, guessing: 0.25, tags: ['design-patterns','solid'] },
  { subTopic: 'Design Patterns', text: 'What does SOLID stand for?', options: [{index:0,text:'Single, Open, Liskov, Interface, Dependency'},{index:1,text:'Single responsibility, Open/closed, Liskov substitution, Interface segregation, Dependency inversion'},{index:2,text:'Scalable, Observable, Linked, Isolated, Decoupled'},{index:3,text:'Stateless, Open, Layered, Integrated, Distributed'}], correctIndex: 1, difficulty: 0.7, discrimination: 1.5, guessing: 0.25, tags: ['design-patterns','solid'] },

  // ── Testing ───────────────────────────────────────────────────────────────
  { subTopic: 'Testing', text: 'What is unit testing?', options: [{index:0,text:'Testing the full application flow end to end'},{index:1,text:'Testing the smallest pieces of code in isolation'},{index:2,text:'Testing with production data'},{index:3,text:'Performance testing under load'}], correctIndex: 1, difficulty: -0.5, discrimination: 1.3, guessing: 0.25, tags: ['testing'] },
  { subTopic: 'Testing', text: 'What is mocking in unit tests?', options: [{index:0,text:'Writing fake user data'},{index:1,text:'Replacing real dependencies with controlled substitutes'},{index:2,text:'Running tests in parallel'},{index:3,text:'Disabling security checks in tests'}], correctIndex: 1, difficulty: 0.2, discrimination: 1.4, guessing: 0.25, tags: ['testing'] },
  { subTopic: 'Testing', text: 'What is Test-Driven Development (TDD)?', options: [{index:0,text:'Testing after deployment'},{index:1,text:'Writing tests before writing the code they test'},{index:2,text:'Using AI to generate tests'},{index:3,text:'Manual testing by QA teams'}], correctIndex: 1, difficulty: 0.1, discrimination: 1.3, guessing: 0.25, tags: ['testing','tdd'] },
  { subTopic: 'Testing', text: 'What does code coverage measure?', options: [{index:0,text:'How many lines are in the codebase'},{index:1,text:'The percentage of code executed during tests'},{index:2,text:'The number of bugs per line'},{index:3,text:'How fast the tests run'}], correctIndex: 1, difficulty: 0.0, discrimination: 1.3, guessing: 0.25, tags: ['testing'] },
  { subTopic: 'Testing', text: 'What is an integration test?', options: [{index:0,text:'A test that mocks all dependencies'},{index:1,text:'A test that verifies how multiple components work together'},{index:2,text:'A test that only checks UI rendering'},{index:3,text:'A test that measures performance'}], correctIndex: 1, difficulty: 0.2, discrimination: 1.4, guessing: 0.25, tags: ['testing'] },
];
